packages/publisher/.vscode/launch.json
packages/publisher/src/generate-packages.ts

Packages with inverted versions -- where the toplevel index.d.ts has a lower version than some /v[0-9]+ subdirectory -- are unexpected by generate-packages. It expects that non-latest versions are always in a subdirectory.
This is not true for react-bootstrap, and no other packages that I'm aware of. I can't remember how react-bootstrap got into this state, but it should not stay there until the issue is actually fixed.
This is just a crash fix, not a complete fix. There aren't any tests because I didn't want to have to add testing infrastructure for generateTypingPackage on short notice -- all the existing tests just test that the correct file contents are generated, not the structure of the generated package itself.
This is not really a complete change, since I'm trying to get a fix out …

Fix crash in inverted version packages

---

.vscode/settings.json
README.md
packages/definitions-parser/src/lib/definition-parser.ts

- Removes "under construction" message in root README
- Removes lerna-specific directions since yarn can be used as usual
- Updates an error message for the new location of dependenciesWhitelist.txt

Update READMEs and messages

---

packages/definitions-parser/src/parse-definitions.ts
packages/dtslint-runner/src/prepareAffectedPackages.ts

I think this was stopping us from responding to webhooks in a timely manner. Probably publisher should be in charge of forking this process out, but 🤷‍♂️

Run parsing in child process even when there’s only 1 CPU

---

packages/perf/package.json
packages/perf/src/cli/compareTypeScript.ts
packages/perf/src/common/db.ts
packages/perf/src/query/index.ts
yarn.lock

This gets rid of a transitive dependency on md5.js
The biggest change is that `query` returns a nested iterator, so it exposes the chunking nature of requesting results.
I think. That's inferred from the type changes. This passes all the tests, but I'm not sure if that's sufficient.

Update @azure/cosmos to 3

---

packages/definitions-parser/src/parse-definitions.ts
packages/publisher/src/util/util.ts
packages/publisher/src/webhook.ts

Follow up on #49—we were never parsing in a child process on Azure, apparently:
https://github.com/microsoft/types-publisher/blob/4ea4d10166d732e294afc8cf755537acd53e02b2/src/lib/common.ts#L38

Use a child process for parsing in production, make log messages better

---

packages/retag/package.json
yarn.lock

Works locally, at least for the `--dry` arg.

Bump yargs from 12->15

---

packages/dtslint-runner/package.json
yarn.lock

This drops a transitive dependency on an old, insecure version of yargs-parser, and makes the npm-naming rule work on the BSD tar that ships with macOS.

Update dtslint dependencies

---

packages/definitions-parser/src/check-parse-results.ts
packages/definitions-parser/src/get-affected-packages.ts
packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/src/packages.ts
packages/definitions-parser/test/get-affected-packages.test.ts
packages/definitions-parser/test/utils.ts
packages/perf/src/cli/compareTypeScript.ts
packages/publisher/README.md
packages/publisher/src/generate-packages.ts
packages/publisher/test/generate-packages.test.ts

Use the more common object format, which is technically less powerful, but we've never needed the additional power of the array format.

Deduplicate dependencies

---

packages/definitions-parser/package.json
packages/header-parser/package.json
packages/publisher/package.json
packages/utils/package.json

Otherwise it's not obvious where the source lives for the corresponding npm packages.
Aside: Why is it owned by microsoft and not in the DT org? Will this be moved later and the links already anticipated this move or are the links outdated in which case: why did it move?

docs: updated repository links

---

packages/utils/src/io.ts

It's only used to download the tgz of DT's master.
I set the timeout to 1000 seconds and added an error-handling line? I don't actually know how node's error handling works so I need to go and learn the right way to do it.
Fixes #64

Add timeout to downloadAndExtractFile

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

https://www.npmjs.com/package/helmet
As of v4.0.0 the package ships is own definition file.
Having package in allowed dependencies list will allow to reference that package types directly in other DTs.
see DefinitelyTyped/DefinitelyTyped#46511
/cc @EvanHahn
Thanks!

feat(helmet): add `helmet` to allowed dependencies list

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Working on types for a module. On `npm test` I got the following error:
```
Error: In package.json: Dependency jsonata not in the allowed dependencies list.
If you are depending on another `@types` package, do *not* add it to a `package.json`. Path mapping should make the import work.
For namespaced dependencies you then have to add a `paths` mapping from `@namespace/library` to `namespace__library` in `tsconfig.json`.
If this is an external library that provides typings,  please make a pull request to microsoft/DefinitelyTyped-tools adding it to `packages/definitions-parser/allowedPackageJsonDependencies.txt`.
```
This is an external library that provides typings.
Repo: https://github.com/jsonata-js/jsonata/blob/master/jsonata.d.ts
Required typings: …

Add `jsonata` to `allowedPackageJsonDependencies.txt`

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Per https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46560, this PR allows `domhandler` in package.json's.

Allow `domhandler` in package.json.

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

moment-timezone now serves its own typings. Add it here so the DT typings can be deleted.
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46421

Allow moment-timezone as package.json dependency

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46626, which references types from `bee-queue`.
(Disclaimer: I'm the primary maintainer for both packages)

feat: allow bee-queue for bull-arena types

---

packages/definitions-parser/src/lib/definition-parser-worker.ts
packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/src/lib/settings.ts
packages/definitions-parser/src/lib/utils.ts
packages/definitions-parser/src/parse-definitions.ts
packages/definitions-parser/test/definition-parser.test.ts
packages/definitions-parser/test/packages.test.ts
packages/publisher/src/parse-definitions.ts

Prevents us from needing to republish/redeploy when allowedPackageJsonDependencies.txt is changed.

Read allowedPackageJsonDependencies from GitHub

---

packages/definitions-parser/src/lib/settings.ts
packages/definitions-parser/src/lib/utils.ts
packages/definitions-parser/src/mocks.ts
packages/definitions-parser/test/definition-parser.test.ts
packages/definitions-parser/test/parse-definitions.test.ts

- Turns out there were no tests that would trigger an `allowedPackageJsonDependencies.txt` download/read (the download is disabled in test runs, but I commented out the env check locally to ensure it works), and a silly `http` vs. `https` module mistake prevented it from working.
- The getter function was previously more complicated because I thought I wanted to log a botched download every time we ask for the list to make sure it’s visible in the long-running types-publisher logs, but changed my mind, since a download issue will be easy to catch in CI.

Fix allowedPackageJsonDependencies download

---

packages/header-parser/src/index.ts
packages/header-parser/test/index.test.ts

typesVersions subfolders are now expected to cover *older* versions with the root having the newest version, and the entry in package.json should be ordered oldest-first now:
For example, a package with 3.2,3.5,3.6 covers these ranges:
3.1-3.2, 3.3-3.5, 3.6, 3.7-4.1
And has the following typesVersions keys:
<=3.2, <=3.5, <=3.6
Publishing this change will block changes to the 18 DT packages that still have typesVersions entries, so I will fix them locally using the prerelease package once this PR is merged.
Edit: Before this change, a package with 3.2,3.5,3.6 covers different ranges and has different typesVersions keys:
3.1, 3.2-3.4, 3.5, 3.6-4.1
with keys:
>=3.6, >=3.5, >=3.2

Flip typesVersions order to oldest-first

---

packages/dtslint-runner/src/index.ts

If `--path` has a default, then it will always conflict with `--clone`, which is causing problems with the On-Demand DT tests for TypeScript

Fix '--clone' vs '--path' conflict due to defaults

---

packages/header-parser/src/index.ts
packages/header-parser/test/index.test.ts
packages/publisher/test/generate-packages.test.ts
packages/typescript-versions/src/index.ts

[According to the schedule](https://github.com/DefinitelyTyped/DefinitelyTyped#older-versions-of-typescript-30-and-earlier), it's time to deprecate 3.1. It seems like not much time since I delayed the 3.0 deprecation to match the 4.0 release.
Removing 3.1 support was complicated. This should be much easier. The follow-up tasks are:
1. Update dtslint and dts-critic.
2. Remove ts3.1/ directories from web-animations-js, openpgp, jest, es-to-primitive.
3. Remove ts3./1 directories from all versions of node. (This is big enough that it deserves its own task; the default implementations will have to move up to the next TS version directory since node's types build up from the oldest versions.)
4. Update "lowest version number" in DT's README.

Deprecate Typescript 3.1

---

packages/perf/package.json
packages/perf/src/cli/benchmark.ts
packages/perf/src/cli/compare.ts
packages/perf/src/cli/compareTypeScript.ts
packages/perf/src/cli/getPackagesToBenchmark.ts
packages/perf/src/cli/index.ts
packages/perf/src/common/utils.ts
yarn.lock

Fixes a bug where `--tsVersion 4.0` is inferred as a number, causing it to stringify as `4`, causing us to look in the wrong directory for the TypeScript installation. Has the added bonus of documenting all CLI options and autogenerating help menus.
I manually sanity-checked by running some commands locally, but plan to test DT’s CI with it by manually triggering runs against `@definitelytyped/perf@next`, which will be published when this is merged to master, prior to publishing a `latest` npm release.

[@definitelytyped/perf] Use yargs for CLI parsing

---

packages/definitions-parser/src/check-parse-results.ts
packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/src/packages.ts
packages/definitions-parser/test/definition-parser.test.ts

Same rationale as #57:
- It's written as if it's unique but isn't, because `getAllUniqueValues()` only does shallow (`===`) equality: https://github.com/microsoft/DefinitelyTyped-tools/blob/d885fe030b7ba7157b89887df403b8538646849f/packages/definitions-parser/src/lib/definition-parser.ts#L223
- I'm not aware of any advantages of the array format. The path mappings are used to refine dependencies and npm allows at most one semver per dependency, so you can't represent anything legal in the array that you can't with an object.
- We end up using the array for object lookup anyway:
- https://github.com/microsoft/DefinitelyTyped-tools/blob/d885fe030b7ba7157b89887df403b8538646849f/packages/definitions-parser/src/check-parse-results.ts#L84
- …

Make path mappings an object

---

packages/definitions-parser/src/lib/module-info.ts
packages/definitions-parser/test/module-info.test.ts

Non-relative reference in typesVersions parent

---

packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/src/lib/module-info.ts
packages/definitions-parser/test/definition-parser.test.ts

Parse the same files as the compiler

---

packages/definitions-parser/src/packages.ts
packages/publisher/src/calculate-versions.ts
packages/publisher/src/generate-packages.ts
packages/publisher/test/generate-packages.test.ts

Previously, the code incorrectly re-used the `@types` package name for the deprecation dependency, which is also noted in the readme as the correct package to install in the future.
This is correct 90%+ percent of the time because `@types/X` usually provides types for package `X`. Sometimes, however, there is no matching `X`, so that `@types/X` should tell users to install some other package `Y` when it's deprecated.
For example, `@types/xumm-api` was for a non-npm package that eventually got published to npm as `xumm-sdk` and at the same time started shipping types. So the deprecation entry looked like this:
```json
{
"libraryName": "xumm-sdk",
"typingsPackageName": "xumm-api",
"sourceRepoURL": "https://github.com/XRPL-Labs/XUMM-SDK",
"asOfVersion": "0.1.4"
}
```
There IS no `xumm-api`, …

Use libraryName for deprecation dependency

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Elasticsearch provides its own typings as of 6.0 https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/6.x/typescript.html
The package `http-aws-es` has this dependency.
The matching DefinitelyTyped PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48112

Add elasticsearch to list of allowed package.json dependencies

---

packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/src/mocks.ts
packages/definitions-parser/test/definition-parser.test.ts
packages/definitions-parser/test/parse-definitions.test.ts

Allow wildcard scope path mappings

---

packages/definitions-parser/src/lib/module-info.ts
packages/definitions-parser/test/module-info.test.ts

microsoft/types-publisher#767
Fixes #35
Fixes #47

Add dependencies for import types

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Elasticsearch's definitions are actually in `@elastic/elasticsearch`, which is already included.
This reverts https://github.com/microsoft/DefinitelyTyped-tools/pull/123 .  Additional context: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48112#discussion_r494450938

Remove elasticsearch from list of allowed package.json dependencies 

---

packages/definitions-parser/src/lib/definition-parser.ts

Put it together with the other `checkFilesFromTsConfig()`/`OTHER_FILES.txt` checks.

Move isRelativePath() from dt-mergebot

---

packages/definitions-parser/src/get-definitely-typed.ts
packages/utils/src/io.ts

Download timeout is still 1000 seconds -- if node's documentation is trustworthy -- so I don't know what is actually hanging.
(It might be 1,000,000 seconds instead of 1,000,000 milliseconds though.)

More logging of DT io in publisher

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

`downshift` includes its own typings: https://github.com/downshift-js/downshift/blob/master/typings/index.d.ts
This is required by this DT PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48446

Include `downshift` in allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

There are couple of definitions that depends on `html-webpack-plugin`
and using old definition type, instead of using inline version shipped
with v4.0.0 of plugin itself.
https://github.com/jantimon/html-webpack-plugin/blob/master/typings.d.ts
Thanks!

Add `html-webpack-plugin`

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Hello!
The bson library now distributes it's own types as of version v4.2.0 and I'm submitting a deprecation but the mongodb types rely on the definitions so `bson` needs to be a permitted package dep.

chore: Add bson to allowPackageJsonDependencies

---

packages/dtslint-runner/src/prepareAffectedPackages.ts
packages/dtslint-runner/src/prepareAllPackages.ts

We'll be testing the types with `minTypeScriptVersion` (modulo `onlyTestTsNext`) so make an effort to get compatible external dependencies by adding the `--tag ts${minTypeScriptVersion}` option to `npm install`. If a dependency provides such a tag then we'll get that compatible version. If not, well, we'll continue to get the current behavior.
This adds the `--tag` option to `prepareAffectedPackages()` (trivial) and `prepareAllPackages()`, which previously used separate logic to crawl the types directory and bypassed `@definitelytyped/definitions-parser`. Adding the `--tag` option means reading the `minTypeScriptVersion`, so I made `prepareAffectedPackages()` and `prepareAllPackages()` share the same logic. I think this is desirable: You should get the same per-package behavior regardless …

Try to get minTypeScriptVersion-compatible dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For [DefinitelyTyped/pull/48886](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48886), which references types from bullmq.

feat: allow bullmq for bull-arena types

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

`helmet` now bundles its types as of 4.0.0, but other package types rely on pre-4.0.0 versions of `helmet`, so `@types/helmet` needs to be added to this list.

Add `helmet` to `allowedPackageJsonDependencies.txt`

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Hi.
`@tween.js/tween.js` now distributes it's own types and I would to like to remove `@types/tween.js`, but `@types/aframe` depends on it https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49024/files#diff-5eda909de686a86eb94de143856c39400ee018575b1dbe36e247b48172696c94R4.

Add @tweenjs/tween.js to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/src/packages.ts
packages/definitions-parser/test/get-affected-packages.test.ts

Honestly, this `tryResolve` method seems extremely suspicious both before and after this change. It returns its input when resolution fails? I’m not sure I see the point. But, it seems to fix the bug, so the enigmatic `AllPackages` will live unscathed for another day, I suppose.
Fixes #118.

[definitions-parser] Fix deleting old versions of packages

---

packages/perf/src/cli/compare.ts
packages/perf/src/common/utils.ts
packages/perf/src/github/postInitialComparisonResults.ts

We previously logged “Skipping react because we ran out of time,” but proceeded to benchmark react immediately afterward.

[perf] Actually fix timeouts when many versions are changed

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

`highlight.js` has its own typings: https://github.com/highlightjs/highlight.js/blob/master/types/index.d.ts
This is required by this pull request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49293
I'm participating in Hacktoberfest, so if you accept these changes please also label the PR as `hacktoberfest-accepted`! Thanks!

Add highlight.js to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/src/packages.ts
packages/definitions-parser/src/parse-definitions.ts
packages/perf/src/cli/benchmark.ts
packages/perf/src/cli/compare.ts
packages/perf/src/cli/compareTypeScript.ts
packages/perf/src/cli/getPackagesToBenchmark.ts
packages/perf/src/common/utils.ts
packages/perf/src/measure/measurePerf.ts
packages/perf/src/query/index.ts

I messed up a bunch of string <---> object version conversions in the perf bot code when trying to adapt to @alloy’s changes that allowed minor version typings directories. You can see a symptom of that mistake [here](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48971#issuecomment-719085291), where both versions of react-dom that are tested are reported as `react-dom/*`. This fix allows `*` to still be used as a version _input_ on the CLI (e.g. `@definitelytyped/perf benchmark react-dom/*`), but should always resolve the `*` to the version number encoded in the header by the time it gets used as outputs (e.g. bot comments or database records).

[perf] Fix versions showing up as "*" all over the place

---

packages/definitions-parser/src/packages.ts
packages/dtslint-runner/package.json
packages/utils/src/process.ts

Most of the changes here improves debugability of `runWithChildProcesses`, but the meaningful change is a follow up to #118 / #147.

Improve error message when other package has a path mapping to a version you’re deleting

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

[Updated definitions of `@ember/component`](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49325) will depend on [types from `ember-cli-htmlbars`](https://github.com/ember-cli/ember-cli-htmlbars/blob/master/lib/index.d.ts).

add ember-cli-htmlbars to allowedPackageJsonDependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Requried for @types/gapi.client.sheets
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49347 and https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49235

Allow to use gapi.client.sheets as a dependency

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Allow @maxim_mazurok/gapi.client.sheets in DT instead of gapi.client.sheets
Related to "A file cannot have a reference to itself." error in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49347

Allow @maxim_mazurok/gapi.client.sheets in DT

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Continuing with #151, the old version of `@types/highlight.js` is still in use by some dependencies and must be installed for their tests to pass.
This is required by this pull request: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49293

Add @types/highlight.js to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Adding `elastic-apm-node` to allowedPackageJsonDependencies.txt
it's needed for this PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49455

feat: adding elastic-apm-node to allowedPackageJsonDependencies

---

packages/perf/src/analysis/metrics.ts

Add `noDiff` to `quickInfoAvgCV`, like `completionsAvgCV`.
Fixes #166

Don't show the difference in mean CV

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

@types/iitc requires old @types/leaflet v0.7
to fix https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49423/commits/e4770b38eee3a5a54f5849b6bc72ac604dffdcb4

Add @types/leaflet to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/src/git.ts
packages/definitions-parser/src/mocks.ts
packages/definitions-parser/src/packages.ts
packages/definitions-parser/test/get-affected-packages.test.ts
packages/definitions-parser/test/git.test.ts
packages/publisher/src/generate-packages.ts
packages/publisher/src/lib/npm.ts
packages/publisher/test/generate-packages.test.ts
packages/utils/src/npm.ts
yarn.lock

Instead of tracking `sourceRepoURL` in `notNeededPackages.json` get it directly from the replacement npm package.
- Move `NotNeededPackage.readme` -> `generateNotNeededPackage()` unchanged except for the reference to `info.homepage` vs. `sourceRepoURL`
- Add `homepage` to `NpmInfo`
- Remove references to `sourceRepoURL`

Use libraryName homepage for not-needed stub

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Adding tapable as an allowed package for use inside of `@types/webpack`.
For use in DefinitelyTyped/DefinitelyTyped#49749

Add tapable as an allowed dependency

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

https://github.com/DefinitelyTyped/DefinitelyTyped/issues/49757
To help facilitate the removal of @types/webpack for pre-5.0.0 and use the internal typings of webpack 5+

Add @types/webpack as an allowed dependency

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Adds two more `gapi.client.*` packages to the allow-list.
Related to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49915 and https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/408

Allow @maxim_mazurok/gapi.client.tasks and workflowexecutions

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Hello! I'm new with Typescript and new in defining types for it, so please tell me if I'm doing something wrong.
I'm going to create the definition types for the following Javascript library: https://github.com/amoshydra/tasker-js-runner, but for that I need the types of another library: https://github.com/Rayquaza01/tasker-types. So, it would be really helpful if "tasker-types"'s library is added to the repository. 
Thank you in advance ;)

Add tasker-types to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

`pg-types` has had bundled TypeScript type definitions for a while now: https://github.com/brianc/node-pg-types/pull/83
I have a PR up to remove `@types/pg-types` up here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49567
`pg` uses `pg-types` and therefore obviously needs its type definitions.

Add pg-types to list of allowed package dependencies

---

packages/header-parser/test/index.test.ts
packages/publisher/test/generate-packages.test.ts
packages/typescript-versions/src/index.ts

Scheduled to happen in January 2021: https://github.com/DefinitelyTyped/DefinitelyTyped#older-versions-of-typescript-31-and-earlier

Deprecate Typescript 3.3

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Adds `@types/express-serve-static-core` to `allowedPackageJsonDependencies.txt`.
Required for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50554.
`@types/express@4.17.10` requires `@types/express-serve-static-core@^4.17.18`.
All versions before `4.17.18` break typing.

Add @types/express-serve-static-core to allowed

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Need it to remove `joi` from DefinitelyTyped without breaking the packages that depend on it
[**`joi/lib/index.d.ts`**](https://github.com/sideway/joi/blob/master/lib/index.d.ts)

Add joi to allowed

---

packages/utils/src/io.ts

Open question:
I'm not sure whether to add a clearTimeout call to `on("error", reject)` -- right now I only put them in things that resemble normal returns.

Add manual timeout to downloadAndExtractFile

---

packages/publisher/README.md
packages/publisher/src/calculate-versions.ts
packages/retag/src/index.ts

Log a before (from cache) and after (from npm) version, plus improve wording slightly.
Also update README to reflect change in publication steps.

Better logging for changed packages

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

The `arweave` package's type definitions are needed in `@types` packages, at [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)
Primarly requesting for [#51035](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51035) in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)

Add arweave to allowed package.json dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

This is to enable `redux-logic-test` types to be added in this PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51057

Add redux-logic as an allowed dependency

---

packages/perf/src/cli/compare.ts

the change I made in https://github.com/microsoft/DefinitelyTyped-tools/pull/204 didn't work as I missed the other checkout command
See https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=87395&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=40b1ee41-44d6-5bba-aa04-4b76a5c732e5
Strangely, as far as I can tell it was failing on the second checkout before #204, but now it's failing on the first checkout instead
Not quite sure how to test this tbh

force checkout

---

packages/utils/src/io.ts

I haven't looked at the source, but Stack Overflow claims there is no timeout by default.

Add timeout to https.request.

---

packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/src/mocks.ts
packages/definitions-parser/test/definition-parser.test.ts
packages/utils/src/miscellany.ts
packages/utils/test/miscellany.test.ts

Given a path mapping as
```
"paths": {
"@ckeditor/ckeditor5-utils": [
"ckeditor__ckeditor5-utils/v10"
]
}
```
definitions-parser failed to understand that `/v10` is not part of the
package name, and that the key of the mapping must be a scoped name.
This PR would unblock https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51335

fix: parser fails with older scoped packages.

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Adds `@jest/reporters` to the dependencies list.
Required for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51600.

Added @jest/reporters to allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Adds dayjs to the dependencies list.
Required for DefinitelyTyped/DefinitelyTyped#51728.

Add dayjs to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Adds `@jest/reporters` to the dependencies list.
Required for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51600.

Add @jest/test-result to allowedPackageJsonDependencies.txt

---

packages/dtslint-runner/expectedFailures.txt
packages/utils/src/process.ts

1. Improve the error message in runWithChildProcesses to pass through the failure reason.
2. Add mithril and mithril-global to expectedFailures, since I haven't found a satisfactory way to make them pass on 4.3 in my two attempts at DefinitelyTyped/DefinitelyTyped#51482 and DefinitelyTyped/DefinitelyTyped#51765.

Improve process logging + expectedFailures addition

---

packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/test/definition-parser.test.ts
packages/utils/src/miscellany.ts

Suppose we have a package called `@ckeditor/ckeditor5-utils` that has an older version `v10`.
The `tsconfig.json` file for the older version must include a path mapping to itself.''
```json
// tsconfig in v10
"paths": {
"@ckeditor/ckeditor5-utils": ["ckeditor__ckeditor5-utils/v10"]
},
```
Currently `definition-parser` ignores any scoped package and does not try to create a path mapping for those.

Fix path mapping not created for older scoped packages

---

packages/publisher/src/lib/npm.ts

The compiler is fine with it, but the constructor expects strict compatibility, not subtype compatibility.
The real fix is not to use constructors, not to assert strict compatibility, and not to use classes at all. I'll look at this after the publisher is working again.

Do not spread processed notneededpackage into raw one

---

packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/test/definition-parser.test.ts

I introduced a node_modules passthrough in webpack in DefinitelyTyped/DefinitelyTyped#51712: the entire index.d.ts is
```ts
import webpack = require('./node_modules/webpack')
export = webpack
```
This allows @types/webpack@5 to delegate its entire type definition to webpack@5, while still allowing @types/webpack@4 to be maintained on DT.
However, the correct module specifier is actually just 'webpack', since there's no guarantee of the exact location where webpack will be installed. This can be made to compile on DT with a path mapping:
```json
"paths": {
"webpack": [
"./node_modules/webpack"
]
}
```
Previously, path mappings like this were not allowed. This PR allows them, of the form `packageName: ["./node_modules/" + packageName]`.

Allow ./node_modules passthrough in paths

---

package.json
packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/test/definition-parser.test.ts
yarn.lock

Turns out that passthroughs need to be allowed anywhere.
Since you can only add passthroughs to `./node_modules`, you can only add passthroughs to things in package.json, which means that that file remains the security bottleneck.

Allow passthrough anywhere.

---

packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/test/definition-parser.test.ts
packages/utils/src/miscellany.ts
packages/utils/test/miscellany.test.ts

* definition-parser: Use scoped names when testing mappings for relative
imports.
* miscellany/utils: When removing version number, keeps wildcard at the
end of mapping.
* miscellany/utils: When checking the existence of a version number,
catch those packages that include a wildcard path mapping.

Fix: Allow /* in scoped versioned mappings.

---

packages/definitions-parser/src/check-parse-results.ts

This should have a test, but writing tests for this is so hard. We should really invest in a system like dt-mergebot has where we can easily generate fixtures for an actual GitHub PR and generate baselines for them.

Fix unused path mapping detection for scoped packages

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

`api-fetch` is required by `data-controls` and publishes its own types since 3.21.2. This PR blocks https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52388

Add @wordpress/api-fetch to allowed dependencies

---

packages/dtslint-runner/expectedFailures.txt

An update to the package makes it no longer directly depend on electron
(which is still broken on new typescripts).

Remove electron-json-storage from expectedFailures.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Adds `serialize-query-params` to the dependencies list.
Required for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52695/files

Adds `serialize-query-params` to allowed package.json dependencies

---

packages/publisher/src/main.ts

`console.error` will allow error messages to show up in App Insights `traces`. I couldn’t find where this `trackEvent` shows up. I’m hoping and assuming that `trackException` will show up in `exceptions`, but the most important thing is having it in logs.

Actually log crashes to STDERR, replace trackEvent with trackException

---

packages/definitions-parser/src/lib/definition-parser.ts

When checkAllUsedRecur fails because of an empty directory, show the
full path to it. Currently "[Object object]" is printed to the terminal.
debugPath does not show path relative to current position, but relative
to root of project.

definition-parser: Show path of empty dir

---

packages/definitions-parser/src/git.ts
packages/definitions-parser/test/git.test.ts

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52719 needs to deprecate @types/socket.io@2 and in doing so modify its dependents. One of its dependents needs to delete a file in its own package (its socket.io test is no longer needed), but this isn't allowed currently.
This changes it to be allowed. I'm not sure I've covered all the interesting cases, so check whether the new code is now too permissive.

Allow deleted files outside notNeededPackages entries

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

add @types/socket.io and @types/socket.io-client to allowed dependencies
as discussed with @sandersn @peterblazejewicz in
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52719#issuecomment-840721803

add @types/socket.io and @types/socket.io-client to allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

[`got`](https://github.com/sindresorhus/got/commits/main/source/index.ts) was reimplemented in TypeScript since [v10](https://github.com/sindresorhus/got/commit/5dac30dff88d1e0821fd143382e39ad74c11b522#diff-fcd423a0b6ae0654240ee2c1cb0b023707df57b7d1c7a3834c5bfbef7d901da5). This MR adds `got` to allowed dependencies in `package.json` files for type definitions on DT.

Allow depending on got in `package.json` on DT

---

packages/dtslint-runner/expectedFailures.txt

The fix is too risky to take for 4.3, so wait until 4.4:
https://github.com/microsoft/TypeScript/issues/43867#issuecomment-830202535
In the meantime, silence the error since it's expected.

add redux-orm to expectedFailures

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

We need to de-couple `readable-stream` from current head of @types/node since readable-stream strictly states it's a [copy of the v10 stream API](https://www.npmjs.com/package/readable-stream).
See corresponding DT PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52732/files#diff-af7da952bbd3d5c94b761da7f4ce4b7b5dac398dd34b890bde3c77719d5191d6R4

chore(node): readable-stream compat

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Webpack 4 DT depends on `anymatch` and @types/anymatch was removed.
This shoudl allow
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53107 to be
merged with fix for failing types.
Thanks!

add(anymatch): update allowed deps list with anymatch

---

packages/definitions-parser/src/packages.ts
packages/publisher/src/generate-packages.ts
packages/publisher/test/generate-packages.test.ts

The idea being that you won't need to pop to GitHub to read the types if it's a small dep.

If the module is a single dts file, show it in the README

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Adds new Google API Types packages into allowedPackageJsonDependencies.txt
Related to https://github.com/Maxim-Mazurok/google-api-typings-generator/issues/499
Blocks https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53354

allow new @maxim_mazurok/gapi.client.* packages

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Mongoose ships its own types starting 5.11
At the same time, there is a dozen or more packages on DT that would
require minor changes to adapt to that change, either by fixing to
already published @types/mongoose or using new native package reference
Ref: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53417
Thanks!

add: mongoose

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Allow tarn package to be added to dependencies as it declares its own types: https://www.npmjs.com/package/tarn

Add tarn to allowed allowedPackageJsonDependencies

---

packages/definitions-parser/src/mocks.ts
packages/definitions-parser/src/packages.ts
packages/definitions-parser/test/packages.test.ts

This means we can't deprecate packages with uppercase letters, but I don't think there are many on npm -- possibly none.

Require lowercase package names in notNeededPackages.json

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Allow msnodesqlv8 package to be added to dependencies as it declares its own types: https://www.npmjs.com/package/msnodesqlv8

Add msnodesqlv8 to allowed allowed deps

---

packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/test/definition-parser.test.ts

This will allow https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53441 to pass.

Allow node/buffer path mapping

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Add [`simple-markdown`](https://github.com/Khan/simple-markdown) to the list of allowed package.json dependencies. Required for the types for discord-markdown (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53501).

Add simple-markdown to allowedPackageJsonDependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

The `sonic-boom` package publishes its own types as of version 2.0.0.  This is a companion PR to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53559.

fix: add sonic-boom to allowed package dependencies

---

packages/utils/src/miscellany.ts
packages/utils/test/miscellany.test.ts

Add support for minor versions when removing the version suffix from a
package name. E.g. @foo/bar@v27.1 should be @foo/bar, but currently the
regexp does not match the dot character.

Fix: remove minor version number from package name

---

packages/dtslint-runner/expectedFailures.txt

@types/vscode-webview is maintained by @mjbvz, and is not on npm, but somebody playing around with vscode-webview created a test package (out of habit I assume). Silence the error until they figure out what to do about it, if anything.

add vscode-webview to expectedFailures

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Reverts microsoft/DefinitelyTyped-tools#276 per @sandersn's indication that it's not necessary.

Revert "Added @types/eslint & co to allowedPackageJsonDependencies.txt"

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

the `buffer` npm package ships its own types

add buffer to allowed package json dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Adding aws-xray-sdk-core because it contains type definitions, as advised by DefinitelyTyped CI.

Add aws-xray-sdk-core

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

The `react-popper` package ships with its own typings
PR with failed pipeline: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53588

Added react-popper to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

The `vite` package ships with its own type definitions.
PR with failed CI: [DefinitelyTyped/DefinitelyTyped#54276](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54276)

Added vite to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

mongodb now ships with its own definitions as of version 4.0.0
PR with failed CI: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54510

Added mongodb to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

I forgot to add this in #290 I'm sorry but this PR just adds `@types/mongodb` to the allowed deps list

Add @types/mongodb to allowedPackageJsonDependencies

---

packages/dtslint-runner/expectedFailures.txt

@types/ng-cordova depends on cordova-plugin-file, which conflicts with the DOM types in TS 4.4. cordova-plugin-file hasn't published a new version in 2 years, so is unlikely to be updated.

Add ng-cordova to expectedFailures.txt

---

packages/dtslint-runner/expectedFailures.txt

Jest needs to upgrade to @types/node@16. I expect this will happen pretty soon, but I tried myself and it wasn't trivial. Now I'm tired of looking at the error -- as soon as it's fixed, the test will fail again and I will remove this entry.

Add jest-environment-puppeteer to expectedFailures

---

packages/utils/src/io.ts

Lots of the CI output in when you use `dtslint-runner` is [noise](https://github.com/microsoft/TypeScript-DOM-lib-generator/runs/3174306610?check_suite_focus=true) - this should reduce that

Remove the audit CLI output

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

`itty-router` ships with its own types. `ThrowableRouter` in DefinitelyTyped/DefinitelyTyped#54960 is a wrapper around `Router` provided by `itty-router`, and thus depends on it.

Add itty-router to allowedPackageJsonDependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

This PR adds `@types/node-fetch` and `node-fetch` to the allowedPackageJsonDependencies since this package recently updated to support its own built-in typings and others will now need to be updated.

Add node-fetch to allowedPackageJsonDependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

The package `rdf-js` which already is on this list is just a [backwards-compatibility proxy which installs](https://github.com/rdfjs/rdf-js/blob/master/package.json#L14) `@rdfjs/types`.
We'd want both allowed here

Add @rdfjs/types

---

.github/workflows/ci.yml
.github/workflows/deploy.yml
.github/workflows/publish.yml
.github/workflows/update-ts-version-tags.yml

My guess is that this will bump the default version of node as well -- it's 10 on v1.

Update setup-node to v2

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56925, so that we can safely upgrade `@types/formidable` without breaking other packages (`restify` specifically)

Add `@types/formidable` to `allowedPackageJsonDependencies`

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

It was incorrectly assumed that it would allow installation of v1 types for Restify, while having v2 types in the DefinitelyTyped repository. Apologies!

Remove @types/formidable

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

`mailparser` requires this package. See [56983](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56983).

Add `iconv-lite` to `allowedPackageJsonDependencies`

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for removal of `express-handlebars` on DT for 3rd party DT
package tests:
DefinitelyTyped/DefinitelyTyped#57137
Thanks!

add(express-handlerbars): new whitelited entry

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

This package is needed for `gulp-ttf2woff2` typings ( https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57152 ).

Add "plugin-error" to allowedPackageJsonDependencies.txt

---

packages/header-parser/test/index.test.ts
packages/publisher/test/generate-packages.test.ts
packages/typescript-versions/src/index.ts

I missed adding 4.6 at the beginning of the RC, so this adds it and ships it in the same commit.

Add+Ship 4.6, deprecate 3.7

---

packages/definitions-parser/src/lib/definition-parser.ts

Some ecosystem packages unconditionally `require` a package's `package.json`, which throws if it's not exported in an export map. While a bundler has no good reason to be inspecting an `@types` package, so we really shouldn't need to be providing a `package.json` entrypoint, including the mapping should fix issues like [this one](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57235#issuecomment-979829788).

Automatically patch a package.json entry onto all object export maps

---

packages/dts-critic/package.json
packages/dtslint/package.json

The other packages have publishConfig setting access: "public", and I think this will correct the lerna problem.

Make new packages public

---

packages/definitions-parser/src/lib/settings.ts
packages/dts-critic/develop.ts
packages/dts-critic/index.test.ts
packages/dts-critic/index.ts
packages/dts-critic/package.json
packages/dts-critic/tsconfig.json
packages/dtslint/package.json
packages/dtslint/src/rules/noUnnecessaryGenericsRule.ts
packages/dtslint/src/suggestions.ts
packages/publisher/src/publish-packages.ts
packages/publisher/src/publish-registry.ts
packages/utils/src/process.ts

1. Use Error casts instead of type annotations to any.
2. Somehow stricter settings didn't apply to dtslint before.
3. Use tsc -b . in dtslint and dts-critic's `build` script.
4. Manually triple-slash reference jest in dts-critic's tests.

Fix dtslint build again

---

packages/dtslint/src/lint.ts

I wish there were a way to redirect tslint's lookup so I didn't have to change every tslint.json on DT.

tslint.json's extends field needs to use @definitelytyped/dtslint now

---

packages/dtslint/src/index.ts
packages/dtslint/src/lint.ts

Instead of .. use ../.. because dtslint shipped source is now at bin/src/*.js instead of bin/*.js
Fixes #362

Fix source-relative paths

---

packages/dtslint/src/checks.ts
packages/dtslint/src/index.ts
packages/dtslint/test/index.test.ts

Also add unit tests to dtslint for the first time ever.
I'm not sure it makes sense to allow any other flags, and eventually exactOptionalPropertyTypes should be required.
Fixes part of microsoft/dtslint#348

allow exactOptionalPropertyTypes in DT tsconfigs

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For DefinitelyTyped/DefinitelyTyped#57611 we need to whitelist this so older packages can remain dependent on the old redis types after we remove them.

add @types/redis to whitelist for backwards compatibility

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

No clean removal path on DT, different versions supported in dependant
modules:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57754
Thanks!

Whitelist `@types/webpack-dev-middleware`

---

packages/dtslint/README.md

Repo https://github.com/Microsoft/dtslint was moved and the package name was not updated.
This commit updates the README accordingly.

README: Use new `@definitelytyped/dtslint` package name

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for v3 (older) support when removing from DT:
DefinitelyTyped/DefinitelyTyped#57847
Thanks!

White-list 'express-rate-limit'

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required to cleanly handle `webpack-dev-server` 4.7.0 changes:
DefinitelyTyped/DefinitelyTyped#57808
Thanks!

whitelist '@types/webpack-dev-server'

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

required for types of alpinejs in DT:
DefinitelyTyped/DefinitelyTyped#58130

whitelist '@vue/reactivity' in allowed package json dependencies

---

packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/src/lib/module-info.ts
packages/definitions-parser/test/definition-parser.test.ts

The list of declared modules includes deep paths, which I think may be correct for general usage, but not for comparing with the list of dependencies, which must be package names.
Found by @chriskrycho while trying to update Ember's types. I didn't take the time to file a bug since it's pretty simple to write a self-contained test.

testDependencies omits entries from 'declare module'

---

packages/dtslint/src/index.ts
packages/dtslint/test/index.test.ts

It leaves DT in an inconsistent state, which causes the publisher to assert.

Forbid adding packages in notNeededPackages.json

---

packages/dtslint/src/index.ts

See also https://github.com/microsoft/dtslint/pull/349 and https://github.com/microsoft/dtslint/pull/350. As soon as an official decision for this issue exists, that should be referenced in the docs as well.
Cherry-picked from https://github.com/microsoft/dtslint/pull/351.

Document banned npm names

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for DefinitelyTyped/DefinitelyTyped#58480 due to its bundled type definitions.

Add javascript-obfuscator to allowed packages

---

packages/definitions-parser/src/check-parse-results.ts
packages/definitions-parser/test/check-parse-results.test.ts
packages/definitions-parser/test/utils.ts

1. Report all unused path mappings of the first unused-having package. Previously it was only the first unused path mapping of the first package.
2. Direct the user to check for missing mappings in dependencies in the case of path mappings that aren't actually unused.
3. Tests! Two of them.
Once again discovered while trying to debug ember v4's types.

Improve unused path mapping error.

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

In order to update the type declarations of `yeoman-environment`, this PR will add the package `execa` to the allowed dependencies.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58614

Add `execa` to the allowed dependencies

---

packages/dtslint-runner/expectedFailures.txt

Looks like jest shipped its new version.

Remove jest-environment-puppeteer from expectedFailures.txt

---

packages/header-parser/test/index.test.ts
packages/typescript-versions/src/index.ts

Update the in-source instructions since @definitelytyped now includes dtslint and dts-critic.

Add 4.7 to supported versions

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

To add @types/vivagraphjs in [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped), these npm dependencies need to be added:
- ngraph.events
- ngraph.fromjson
- ngraph.graph
- ngraph.merge
- ngraph.random
- ngraph.tojson

vivagraphjs: add vivagraphjs npm dependencies with types definition in it

---

packages/publisher/src/generate-packages.ts

in generateNotNeededPackages. Left over from github publisher removal.

Remove duplicated writeCommonOutputs call

---

packages/dtslint/src/index.ts
packages/dtslint/test/index.test.ts

dtslint asserts that a package's path is
1. in a DT-like structure -- one with types and packages inside that
2. not in notNeededPackages.json -- this requires reading it from the DT
root
3. not on a list of names that npm bans for being spammy
This PR calculates the DT root independently for and provides it for (1) and (2). Previously only (1) calculated the root and (2) just assumed that notNeededPackages was in the right location relative to the current working directory.

Find DT root for path assertions

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

We are removing DT definition relyng on this rule:
DefinitelyTyped/DefinitelyTyped#56658
This will be no longer need,
Thanks!

remove(vfile): disallow dependency

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

In order to create the type declarations of `cobe`, this PR will add the package `phenomenon` to the allowed dependencies.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58852

Add `phenomenon` to the allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

I want to use this to replace `jest.Expect` in `@types/jest` with the version from Jest itself.
This is the module that provides `expect` internally in Jest.
Source: https://github.com/facebook/jest/blob/main/packages/jest-expect/package.json
See https://github.com/facebook/jest/issues/12424

chore: add `@jest/expect`

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

In order to create the type declarations of gulp-stylelint, this PR will add the package stylelint to the allowed dependencies.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58898

Add `stylelint` to the allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

cssnano now ships its own types, so this is setting the infrastructure up to deprecate @types/cssnano by adding `cssnano` to the allowed dependencies.

Add cssnano to the allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Add `node-canvas` to the allowed dependency list.
Required for this PR [DefinitelyTyped/DefinitelyTyped#59177](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59177)

Added `canvas` to the allowed dependencies

---

packages/dtslint-runner/expectedFailures.txt

These are passing again, apparently.

Remove vscode-webview and sketchapp from expected failures

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

ioredis now ships its own types as of v5 (https://github.com/luin/ioredis/wiki/Upgrading-from-v4-to-v5), so ioredis would need to be allowed dependency to reference ioredis in dependent type packages and deprecate @types/ioredis.

chore: add ioredis to the allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

https://github.com/DefinitelyTyped/DefinitelyTyped/runs/5853633195?check_suite_focus=true#step:6:13
[acorn](https://www.npmjs.com/package/acorn) contains built-in TypeScript declarations, @types/detective depends on the deprecated DT types.

Add @types/acorn to allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

https://github.com/DefinitelyTyped/DefinitelyTyped/runs/5854418101?check_suite_focus=true#step:6:13
- [hapi](https://www.npmjs.com/package/hapi) is a deprecated npm package: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59709
- @types/swagger-node-runner depends on v16 of the DT types.

Add @types/hapi to allowed dependencies

---

packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/src/mocks.ts
packages/definitions-parser/src/packages.ts
packages/publisher/test/generate-packages.test.ts

Adds some static checks: `` `${major}.${minor}` `` is assignable to `` `${number}.${number}` `` whereas `'1'` and other strings aren't.

Type-check some version strings

---

packages/dtslint/README.md
packages/dtslint/src/rules/expectRule.ts
packages/dtslint/test/expect/expectType.ts.lint

_(Ported from https://github.com/microsoft/dtslint/pull/356 since it appears that repo is no longer active)_
---
When updating TypeScript definitions for DefinitelyTyped, I encounter the following error:
```
ERROR: 19:1  expect  TypeScript@4.7: Can not match a node to this assertion.
```
I found an open issue in this repo which mentions the issue, but the specifics of the situation seems unrelated: https://github.com/microsoft/dtslint/issues/157, and it wasn't until I found this comment that I understood what the problem was: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51161#issuecomment-777039728:
> Ok in dtslint readme there's two ways of using it: before and at the end of the line. So I guess the multiline structure is thee cause of the problem.
In this instance Prettier …

Add more detail to dtslint error message

---

packages/dts-critic/index.ts

Any OS can pretty much have any tar:
- Windows now ships with bsdtar at `C:\System32\tar.exe`, but people can also get tar while inside cygwin/msys/git-bash, which is likely GNU tar.
- macOS ships with bsdtar too, but it's also possible to install GNU tar via `brew` and replace the system one (like one can replace ssh, python, zsh, etc).
- Linux is effectively always GNU tar, though some distros offer bsdtar as a `bsdtar` executable.
But, there's thankfully only two tar implementations still around, bsdtar and GNU tar, so rather than using the platform, just check which tar is being used before passing `--warning=none`.
`downloadNpmPackage` is not a hot function; it's called only once, so this shouldn't cause any overhead issues.
Previously:
- …

Check for bsdtar explicitly before passing --warning=none

---

packages/utils/.gitignore
packages/utils/package.json
packages/utils/src/io.ts
packages/utils/src/types/tar.ts
packages/utils/test/data/pack/test.txt
packages/utils/test/io.test.ts
yarn.lock

Updated the old `tar` dependency to the latest version and used its new API.
The `@types/tar` package seems to be incorrect (it shows the old API), so I decided to remove it completely. As the `tar` package is used in just one place, I think it's not a big deal to use the untyped library.
I haven't been able to definitely verify if setting directory permissions still works. 7Zip on Windows shows full permissions on the packed directory, but I haven't checked it on Linux yet.
Closes #347

Update tar dependency

---

packages/retag/src/index.ts

Fixes https://github.com/microsoft/DefinitelyTyped-tools/issues/443#issue-1219123741
This was my fault: https://github.com/microsoft/DefinitelyTyped-tools/pull/436/files#diff-db845ec0d026f55c2d985945bf1ca7668fe32dff8ea2251dc000a7009a3a4bf7R150
Landing this fix and [manually triggering](https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow) the [Update ts* tags for ATA](https://github.com/microsoft/DefinitelyTyped-tools/actions/workflows/update-ts-version-tags.yml) action will fix the issue and repair npm's tags. Only the tags are affected.

Fix npm dist-tags

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Add @types/lru-cache as lru-cache now declares its own typings and other packages rely on older typings.
see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60297

Add @types/lru-cache to allowedPackageJsonDependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

This package now provides its own typings and is a dependency of other typings. Please see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60315

add asn1js as allowed package depenency

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

In the DefinitelyTyped repository, I added a [draft PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60362) updating typings for the mParticle SDK.  When the tests ran, I received [this error](https://github.com/DefinitelyTyped/DefinitelyTyped/runs/6457645722?check_suite_focus=true#step:6:16) telling me I had to submit a PR to add an package as an allowable dependency in order to use it in the mParticle typings package.json file.

feat: add @mparticle/event-models to allowed packages

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

- `@types/libnpmpublish` [uses the `pacote.Manifest` type](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/1d42fa0682cef252716f061f304ec69de88d5464/types/libnpmpublish/index.d.ts#L29) for the publish() argument although `libnpmpublish` doesn't require a `dist` field: The argument can be a parsed package.json.
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60433 makes additional `pacote.Manifest` fields required ([`_id`, `_nodeVersion`, etc.](https://github.com/npm/registry/blob/master/docs/responses/package-metadata.md#:~:text=each%20package%20version%20data%20object%20contains%20all%20of%20the%20fields%20in%20the%20abbreviated%20document%2C%20plus%20the%20fields%20listed%20above%20as%20hosted%2C%20plus%20at%20least%20the%20following%3A)).
- To keep the CI passing, it …

Add @npm/types to allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Allow DefinitelyTyped types to depend on @aws-sdk/client-s3. This is to unblock https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60684

Allow @aws-sdk/client-s3 dependency

---

packages/utils/src/lib/settings.ts
packages/utils/src/npm.ts

I’m not sure why this was changed in #451 but it breaks production because the app lives on a read-only filesystem.

Fix cache dir path

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Add [`pino`](https://www.npmjs.com/package/pino) and [`pino-http`](https://www.npmjs.com/package/pino-http) to the list of allowed dependencies, since these packages come with their own typings now.
npm: [`pino`](https://www.npmjs.com/package/pino) | npm: [`pino-http`](https://www.npmjs.com/package/pino-http)
---|---
This will help fix the build for `@types/koa-pino-logger`, which has been reported as flaky a few times.
Related PR: [(Koa) Specify the response body type for Koa #60767](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60767)

Add `pino` and `pino-http` to the list of allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Add [`pino-pretty`](https://www.npmjs.com/package/pino-pretty) to the list of allowed dependencies, because it's shipped with its own typings.
This will help fix the build for `@types/koa-pino-logger`, which has been reported as flaky a few times.
Related PR: [(Koa) Specify the response body type for Koa #60767](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60767)
Previous PR: [Add `pino` and `pino-http` to the list of allowed dependencies #481](https://github.com/microsoft/DefinitelyTyped-tools/pull/481)

Add `pino-pretty` to the list of allowed dependencies

---

packages/definitions-parser/src/packages.ts
packages/definitions-parser/test/packages.test.ts
packages/publisher/src/calculate-versions.ts
packages/publisher/src/lib/npm.ts
packages/publisher/src/publish-registry.ts
packages/retag/src/index.ts
packages/utils/src/npm.ts

I didn't have any luck tracking down when exactly this changed, but the npm registry hasn't needed %2f-encoding for some time, I think? e.g. https://registry.npmjs.org/@types/node
Can we remove the `fullNpmName`/`fullEscapedNpmName` distinction, in view of the similar but unrelated `unescapeName()`: https://github.com/microsoft/DefinitelyTyped-tools/blob/575fd10bc80d3fb50135a429855a3b0864983a95/packages/definitions-parser/src/packages.ts#L203-L204

Registry API no longer needs %2f-encoding

---

packages/dtslint/src/lint.ts

The last part of the check was backward, so it forbid `eslint-disable rule-name` but not `eslint-disable` on its own.

Fix eslint-disable check

---

packages/definitions-parser/src/lib/definition-parser.ts
packages/utils/src/fs.ts

The FS wrapper and unused-files check both need to know about .eslintrc.json.
The FS check for `./foo` is too simple, but I expanded the existing allow-list instead of making the check stricter.

Allow .eslintrc.json

---

packages/utils/src/typescript-installer.ts

This is to solve https://github.com/DefinitelyTyped/DefinitelyTyped/issues/61184 where `installAllTypeScriptVersions()` might get called with `NODE_OPTIONS="--require source-map-support/register"` in the environment, thus failing the installation

[utils] Remove `NODE_OPTIONS` env variable if it contains `--require` when calling `installAllTypeScriptVersions()`

---

packages/dtslint-runner/expectedFailures.txt

sparql-http-client is the one package currently exhibiting a conflict between DOM and node's versions of the AbortSignal type. [I tried to break the DOM dependency by copying the required types into the package](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60749), but that's clunky and brittle.
Few people use this package so I think it's better to ignore the failure until we come up with a comprehensive dual-environment solution.

Add sparql-http-client to expectedFailures

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for DefinitelyTyped/DefinitelyTyped#60883, since minipass now bundles its own types.

Add minipass to allowed packages

---

packages/dtslint-runner/src/main.ts

This change should allow https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61001 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61620 to pass CI

Allow expected failures in dependents

---

packages/dtslint/dt.json

The rule is now in `.eslintrc.json` files, so I _think_ this is right and will get rid of these messages on DT:
```
Could not find implementations for the following rules specified in the configuration:
dt-header
Try upgrading TSLint and/or ensuring that you have all necessary custom rules installed.
If TSLint was recently upgraded, you may have old rules configured which need to be cleaned up.
```
/cc @JoshuaKGoldberg

Remove dt-header from tslint config

---

packages/publisher/src/generate-packages.ts
packages/publisher/test/generate-packages.test.ts

The order of dependencies in the README of `@types/...` packages changes depending on how the object is constructed in [this function](https://github.com/microsoft/DefinitelyTyped-tools/blob/master/packages/publisher/src/generate-packages.ts#L172-L194). 
This PR changes the order so that it is always consistent. This reduces the diff when a package is updated.

[publisher] use consistent order for dependencies in the generated README

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Adding `filestack-js` to the allowed dependencies. It's required for types definitions for `filestack-react`.
[Related PR in DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62164)

Added `filestack-js` to allowed `package.json` dependencies

---

packages/dtslint/src/checks.ts

Require a ">4.9.0-a" entry to handle 4.9 beta and dev releases.

Special case node's typeVersions for 4.9 beta

---

packages/dtslint/src/checks.ts
packages/header-parser/src/index.ts
packages/header-parser/test/index.test.ts
packages/typescript-versions/src/index.ts

Work around the bug in Typescript semver semantics by using a more precise specifier that works there, as well as standard semver.
The bug in typescript should be fixed soon, so we can change this back later. In the meantime only 13 packages use typesVersions so it's easy to change back and forth.
Also get rid of the node-specific special-case in typesVersion checking, which wouldn't have worked for publishing in any case.

Change typesVersions format

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Similar to #463, #311 and other PRs by me:
- adding new Google APIs
- removing APIs that are removed from google discovery and removed from DT as well
Removed APIs do not exist in DT so shouldn't cause any trouble:
- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gapi.client.run-v1alpha1
- https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/gapi.client.speech-v2beta1

gapi.client.* updates

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

In order to complete https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62783, I've followed the readme and added rvagg's "bl" to the list. Let me know if I made any mistake 😄

Added bl to allowedPackageJsonDependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

we need this since fs-capacitor's types will soon be removed from DT (they ship their own types now).
one package remains in DT which depends on fs-capacitor, so will need it as a dependency.

chore (definitions-parser): add fs-capacitor to whitelist

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

similar to #548 we need to whitelist bull so the `bull-arena` package can depend on it in DT once we drop bull's types for the shipped ones

chore (definitions-parser): add bull to whitelist

---

packages/dtslint-runner/expectedFailures.txt

Fixed by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62782

Remove storybook dependents from expectedFailures.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62843
Since the PollyJS team already implemented the types, we could add the following library into the notNeededPackages.json
```
... 
"pollyjs__adapter": {
"libraryName": "@pollyjs/adapter",
"asOfVersion": "6.0.4"
},
"pollyjs__adapter-fetch": {
"libraryName": "@pollyjs/adapter-fetch",
"asOfVersion": "6.0.5"
},
"pollyjs__adapter-node-http": {
"libraryName": "@pollyjs/adapter-node-http",
"asOfVersion": "6.0.5"
},
"pollyjs__adapter-puppeteer": {
"libraryName": "@pollyjs/adapter-puppeteer",
"asOfVersion": "6.0.5"
},
"pollyjs__adapter-xhr": {
"libraryName": "@pollyjs/adapter-xhr",
"asOfVersion": "6.0.5"
},
"pollyjs__core": {
"libraryName": "@pollyjs/core",
"asOfVersion": "6.0.5"
},
"pollyjs__node-server": {
"libraryName": …
```

Add @pollyjs/core as allowed dependency 

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

one package in DT still depends on it, so we need to whitelist for now

chore (definitions-parser): whitelist prosemirror-view

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

would be useful to be able to pull these shipped types into dependent dt types
i added the types package equivalents too since some unmaintained packages may need those (before puppeteer shipped types)

chore (definitions-parser): whitelist puppeteer

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Working on updating the types for the `prompts` package, which requires the types published by package `kleur`.

Add kleur as an allowed dependency

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

I wish to add type definitions for the module swagger2openapi, but it depends on openapi-types and the contribution guide says it needs to be added here first
ref: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63631

Add openapi-types to allowed packages

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

The current `workbox-build` typing reference inside the [@types/next-pwa](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/next-pwa) package points to `@types/workbox-build`, which has not updated its definitions since `v5.0` of the parent module. Currently, the original `workbox-build` package sits at `v6.5.4`. This package version mismatch may compromise the extended [webpackConfigOptions](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/next-pwa/index.d.ts#L44) type referenced within the `@types/next-pwa` package. 
To solve this issue, adding the dependency to the allowed packages list will ensure that the reference won't ripple any **possibly** stale and/or mismatched types.

Add `workbox-build` to allowed packages

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

There are multiple now-stale `workbox-_` DT packages that need to be removed, and in doing so, the original bundled definitions will be the default dependency. This PR adds only one more to the list, but many more may need to be added going foward.
- [CI job error](https://github.com/DefinitelyTyped/DefinitelyTyped/commit/546d5ccd80955ef4aa9d35c4eb336e1f3365e450/checks?check_suite_id=10018574487#step:6:14)
- [PR to remove workbox-_ DT packages](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63682) 
- [DT discord thread where the issue first surfaced](https://discordapp.com/channels/508357248330760243/1055115632372371496)
`workbox-webpack-plugin` is a dependency inside the [customize-cra DT package](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/customize-cra/ …

Add `workbox-webpack-plugin` to allowed packages

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Allow generic-pool and @types/generic-pool as dependency for types packages.
Required by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63876

Allow generic-pool and @types/generic-pool

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for DefinitelyTyped/DefinitelyTyped#64062, since @types/react-leaflet-markercluster depends on a version of react-leaflet that doesn't bundle its own types.

Add @types/react-leaflet to allowed packages

---

packages/dtslint-runner/expectedFailures.txt

I switched these packages to depend on @types/aws-sdk2-types instead of full aws-sdk@2, since they are unlikely ever to upgrade to version 3.

Remove more AWS dependents from expectedFailures.txt

---

packages/dtslint-runner/expectedFailures.txt

I updated them so that https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63878 would pass.

Remove the last aws-sdk@2 dependents from expectedFailures

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

some old packages still depend on the old types.
for DefinitelyTyped/DefinitelyTyped#64246

chore (definitions-parser): whitelist micro package

---

packages/dtslint-runner/src/index.ts
packages/dtslint-runner/src/main.ts
packages/dtslint/src/index.ts
packages/dtslint/src/rules/noRedundantJsdoc2Rule.ts

1. 2 typo fixes
2. explain what `--noInstall` does for dtslint-runner so we keep it around. (it's for when you've run dtslint-runner locally recently and don't need to `npm install` every package -- that takes about an hour each time.)
3. Use `slice` instead of `substr`, which is deprecated.
4. Add support for JSDocThrowsTag using the workaround for the dependency that doesn't have it in its enum.

4 small fixes

---

packages/utils/src/process.ts

See if it stops out-of-memory crashes, even though it will be considerably slower.

Stop and restart each dtslint individually

---

packages/utils/src/process.ts

50 tasks per child avoids about 80% of ooms without slowing down tests much at all. Let's see if 20 tasks per child will avoid closer to 100% without slowing down too much more.

Try only 20 tasks per child instead of 50

---

.eslintrc.json
packages/dtslint-runner/expectedFailures.txt
packages/dtslint-runner/src/index.ts
packages/dtslint-runner/src/main.ts
packages/dtslint-runner/src/types.ts
packages/utils/src/process.ts

Also remove `fhir` from expected failures, which passes every time now that memory pressure is relieved.

Add child restart interval flag

---

packages/dtslint/src/lint.ts

expectRule hasn't been ported, so no need to run eslint when --expectOnly is provided.
Easier to review with whitespace turned off.

Skip eslint in --expectOnly

---

packages/dtslint-runner/src/main.ts
packages/dtslint/src/lint.ts
packages/dtslint/src/rules/noRedundantJsdoc2Rule.ts

1. typescript-eslint memory usage workaround provided by @bradzacher in https://github.com/typescript-eslint/typescript-eslint/issues/6462. Clear caches after each run so that ts.Program objects aren't retained forever.
2. typescript-eslint speedup provided the same way. Avoid constructing some objects that are only needed for editors.
3. Add yet another jsdoc tag to no-redundant-jsdoc2
4. Correct and reduce amount of perf-related printing at end of ExpectRule. The correction is needed now that ExpectRule saves the equivalent of --extendedDiagnostics after running; I changed the name of the properties to match.

typescript-eslint workaround + misc fixes

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

i actually whitelisted react-router and react-router-dom in this too as ill soon be opening a PR around that over at DT too.
all are depended on by other DT packages (or will be imminently)

chore (definition-parser): whitelist react-router-native

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Needed for three.js types, since three.js re-exports lil-gui (see https://github.com/three-types/three-ts-types/pull/358).

Add lil-gui to allowed dependencies

---

packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/src/lib/module-info.ts
packages/utils/src/fs.ts
packages/utils/test/fs.test.ts

Imports of ambient module names won’t resolve to local files without the use of the type checker, and are supposed to be ignored during used file detection. But instead, they might resolve to something in a rogue ancestor node_modules present on the CI runner. This makes the module resolution host pretend those files don’t exist.

Ignore files outside of DT repo for module resolution when detecting used files

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Needed for three.js types, since three.js re-exports fflate.

Add fflate to allowed dependencies

---

packages/definitions-parser/src/lib/module-info.ts
packages/definitions-parser/test/definition-parser.test.ts

getModuleInfo's per-node handling of top-level statements in a non-module sourcefile forgot to include EmptyStatement.

Handle EmptyStatement at top-level in global files

---

packages/dtslint/README.md

This came up in a DT PR review, where the author thought they had to specify the version if it needed something newer than 2.0.
Maybe the example should say something newer too.

Link to DT support window rather than mentioning TS 2.0

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

This is because as of 9.0.0, glob has its own types
Look at the DefinatelyTyped repo PR for more details:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64810
I have raised this PR because while trying to create the said PR above, I received this error:
```bash
Error: In package.json: Dependency @types/glob not in the allowed dependencies list.
Don't use a 'package.json' for @types dependencies unless this package relies on
an old version of types that have since been moved to the source repo.
For example, if package *P* used to have types on Definitely Typed at @types/P,
but now has its own types, a dependent package *D* will need to use package.json
to refer to @types/P if it relies on old versions of P's types.
In this case, please make a pull request to …
```

Add @types/glob to list

---

packages/utils/src/io.ts

Unbreaks `wordpress__block-editor`.

Pass --legacy-peer-deps at npm install

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

think im gonna need this for some of the really old packages when i remove the react-router types
a few use types no longer available in the new react-router, with no obvious equivalent. so ill keep them on the old DT types for now

chore (definitions-parser): whitelist react-router

---

packages/dtslint/dtslint.json

Remove no-import-default-of-export-equals from dtslint.json

---

packages/dtslint/src/rules/no-import-default-of-export-equals.ts
packages/dtslint/test/no-import-default-of-export-equals.test.ts

looks like it's `data: Record<string, any>` instead of `data: Record<string, string>`!
Edit: There are lots of failures overnight that don't happen on my machine. I'll fix that here too.

fix no-import-of-default-export

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Specifically for this MR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64939
`ramda` is moving type definitions in house with in the intention for those types to exist within the main `ramda` package. In the meanwhile, `@types/ramda` will re-export the new `types-ramda` package while we solidify the existing types and work on the next `ramda` release that will include those types in-package

Add types-ramda to allowedPackageJsonDependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

`@wordpress/components` now ships types (see https://www.npmjs.com/package/@wordpress/components)
Since I'd like to remove the DT types here (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65213), and since we now need to use npm to import this package for some other `@types/wordpress` packages, it should be added to this lsit

Add wordpress components to allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Adding [@react-native/virtualized-lists](https://www.npmjs.com/package/@react-native/virtualized-lists?activeTab=versions) to allowed dependencies as React Native 0.72 typings depend on it. 
Adding this here because of the error running `yarn test-all` in DefinitelyTyped
```
Error: In package.json: Dependency @react-native/virtualized-lists not in the allowed dependencies list.
If you are depending on another `@types` package, do *not* add it to a `package.json`. Path mapping should make the import work.
For namespaced dependencies you then have to add a `paths` mapping from `@namespace/*` to `namespace__*` in `tsconfig.json`.
If this is an external library that provides typings,  please make a pull request to microsoft/DefinitelyTyped-tools adding it to …
```

Add @react-native/virtualized-lists to allowed deps

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65283

Add googleapis to allowed dependencies

---

packages/publisher/package.json
packages/publisher/src/full.ts
packages/publisher/src/get-definitely-typed.ts
packages/publisher/src/main.ts
packages/publisher/src/publish-packages.ts
yarn.lock

Based on an analysis of azure usage with @RyanCavanaugh.
This hasn't worked for a long time, because there's a bug in the publish notification code that runs before the call to application insights. I'm not sure whether to delete *that* or to fix it. Publication has been reliable (and predictable!--since the Functions changeover) for a long time so neither the notification nor the stats are as necessary as they once were.

Remove applicationinsights

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Add gray-matter to the allowed dependencies for DefinitelyTyped definitions.  I am updating `@types/metalsmith`, and the updates include a reference to `gray-matter`.

Add gray-matter to allowed dependencies

---

packages/utils/src/typescript-installer.ts

Fixes #677
See that bug for discussion; it's somewhat complicated, but the fix is: during RC you have to install the RC as well, just in case.

Fix RC installation

---

packages/dtslint/src/lint.ts

Fixes
```
AssertionError [ERR_ASSERTION]: The expression evaluated to a falsy value:
assert(minIdx >= 0)
at range (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint-runner/node_modules/@definitelytyped/dtslint/src/lint.ts:261:3)
at getLintConfig (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint-runner/node_modules/@definitelytyped/dtslint/src/lint.ts:239:28)
at lint (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint-runner/node_modules/@definitelytyped/dtslint/src/lint.ts:40:18)
at testTypesVersion (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/@definitelytyped/dtslint-runner/node_modules/@definitelytyped/dtslint/src/index.ts:233:15)
at runTests …
```

Lint against supported TS versions not just shipped

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for the DefinitelyTyped update to remove `flatbush` there (required for `geoflatbush`)
https://github.com/mourner/flatbush/releases/tag/v4.2.0

Add flatbush to allowed dependencies now that it ships its own types

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for https://github.com/three-types/three-ts-types/pull/514.

Add meshoptimizer to allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

ember-source ships types directly as a replacement for the @types/ember types in newer versions of ember.js
required for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66086

add ember-source as allowed dependency

---

packages/utils/src/typescript-installer.ts

Hi,
We'd like to install some old versions to test the generated types to check compatibility, but current exposed `installAllTypeScriptVersions` can only install the supported (shipped/rc/next) versions.
So I want to suggest exporting the `install` function to enable the ability to install any needed version of typescript.
(Resolves #434)
Thank you.

feat: export `install` function from typescript-installer

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Aggregate error is a package uses by semantic-release, and is required for the type definitions for v21.
https://www.npmjs.com/package/aggregate-error
PR on DT: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66223

feat: Added aggregate-error to allowed dependencies

---

packages/dtslint/dtslint.json
packages/dtslint/src/lint.ts

See: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65703#discussion_r1282552441
This will be replaced with `@typescript-eslint/ban-ts-comment` in the eslint config in the DT repo (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66274)

Remove ts-ignore check, to be replaced with eslint rule

---

packages/header-parser/test/index.test.ts
packages/typescript-versions/src/index.ts

To be merged after 5.2 has its own branch and `typescript@next`'s version is 5.3

Support 5.3

---

packages/header-parser/test/index.test.ts
packages/typescript-versions/src/index.ts

This reverts commit fd2b71c01ad75fb3daba0c3654846743ca4e041b.
This is #703 again, but shouldn't be merged until Tuesday.

Revert "Revert "Support 5.3 (#703)" (#704)"

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

In support of https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66413.

Add markdownlint as allowed package.json dependency

---

packages/dtslint/dtslint.json

These are only the ones that fail on a full run; in theory any of them could fail at any time because they nearly all import tsutils, which uses Identifier.originalKeywordKind, the property that is deprecated in TS 5.0.
I don't think any of these are worth looking for an eslint equivalent.

Disable tslint rules broken in TS5.0

---

packages/dtslint/dtslint.json

Followup to #699. @sandersn pointed out that it was missed - I hadn't realized dprint covers this too!

feat: remove comment-space from dtslint.json too

---

package.json
packages/dtslint/src/lint.ts
packages/dtslint/src/rules/expectRule.ts
packages/dtslint/src/rules/noRedundantJsdoc2Rule.ts
packages/eslint-plugin/src/rules/no-dead-reference.ts

Fail the CI/Local build if we are using eslint-disable spuriously.
More information -> [here](https://eslint.org/docs/latest/use/command-line-interface#:~:text=%2D%2Dreport%2Dunused%2Ddisable%2Ddirectives,-This%20option%20causes&text=This%20can%20be%20useful%20to,which%20are%20no%20longer%20applicable.&text=When%20using%20this%20option%2C%20it,or%20custom%20rules%20are%20upgraded.)
It's a bit confusing seeing `eslint-disable` on some of the violations like the `@ts-ignores` and some not.
This either was due to accidentally removing that rule or we no longer want to enforce, if the latter, lets clean it up.
Unfortunately, eslint **only** errors if we have this as part of the CLI Arguments `--report-unused-disable-directives`.
```
/Users/marcinstrzyz/src/DefinitelyTyped-tools/packages/dtslin …
```

chore: Audit unused eslint disables.

---

packages/eslint-plugin/package.json
packages/eslint-plugin/src/rules/no-declare-current-package.ts
packages/eslint-plugin/src/rules/no-self-import.ts
packages/eslint-plugin/src/util.ts
packages/eslint-plugin/test/no-declare-current-package.test.ts
packages/eslint-plugin/test/no-self-import.test.ts
packages/eslint-plugin/test/util.test.ts

I think the existing `getCommonDirectoryName` helper wasn't returning the actual package name. So this should make the behavior more accurate, I think. I'm not sure.

fix(eslint-plugin): [no-self-import] account for nested ('grandparent') path names

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Add [@serverless/typescript](https://www.npmjs.com/package/@serverless/typescript) to allowed dependencies to allow new type definitions for [serverless-step-functions](https://www.npmjs.com/package/serverless-step-functions) to depend on it.
PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66693
CI failed due to unallowed dependency:
```
Error: In package.json: Dependency @serverless/typescript not in the allowed dependencies list.
If you are depending on another `@types` package, do *not* add it to a `package.json`. Path mapping should make the import work.
For namespaced dependencies you then have to add a `paths` mapping from `@namespace/*` to `namespace__*` in `tsconfig.json`.
If this is an external library that provides typings,  please make a pull request to …
```

Add @serverless/typescript to allowed dependencies

---

.changeset/early-yaks-explode.md
packages/dtslint-runner/src/prepareAffectedPackages.ts

I am getting so massively tired of DT runs failing on PRs due to npm install.
This PR adds a silly retry loop as I'm pretty sure this is a transient npm problem made worse by the fact that we invoke npm a billion times.

Retry npm install on failure in dtslint-runner

---

.github/workflows/version-or-publish.yml
package.json

This has to be done manually when not using `changeset publish`.
While here, drop the env var from the format step; it's preserved from checkout and isn't used there.

Tag during publish in changeset action

---

.changeset/rude-geese-bow.md
packages/dtslint/dt.json

It's part of tslint:all and needs to be disabled explicitly. Mistake in #684 that I didn't catch because I didn't run it on DT.

Turn off no-redundant-jsdoc explicitly

---

package.json
packages/retag/package.json

It's index.js now, not retag.js.

Fix retag bin name

---

packages/definitions-parser/src/get-affected-packages.ts
packages/definitions-parser/src/git.ts
packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/src/packages.ts
packages/definitions-parser/test/get-affected-packages.test.ts
packages/definitions-parser/test/git.test.ts
packages/definitions-parser/test/packages.test.ts
packages/definitions-parser/test/parse-definitions.test.ts
packages/definitions-parser/test/tsconfig.json
packages/definitions-parser/test/utils.ts
packages/header-parser/src/index.ts
packages/publisher/src/calculate-versions.ts
packages/publisher/src/generate-packages.ts
packages/publisher/src/lib/npm.ts
packages/publisher/src/lib/package-publisher.ts
packages/publisher/src/lib/versions.ts
packages/publisher/src/publish-packages.ts
packages/publisher/src/publish-registry.ts
packages/publisher/src/util/util.ts
packages/publisher/test/generate-packages.test.ts
packages/retag/src/index.ts
packages/utils/package.json
packages/utils/src/typescript-installer.ts
packages/utils/test/io.test.ts
packages/utils/test/typescript-installer.test.ts
pnpm-lock.yaml
tsconfig.json

A bunch of renaming, and preserving some more info starting at the header parser. New nomenclature:
- name: `@types/ember__object`
- typesDirectoryName: `ember__object`
- libraryName: `@ember/object` (or `nonNpmDescription` for non-npm packages)
- subDirectoryPath: `ember__object/v2`

Rename name-related fields

---

.github/workflows/publish-packages.yml
packages/publisher/src/main.ts

The other things we run don't seem to actually need the installed state so the memory FS is probably fine. So this is a targeted fix specifically for publishing.

Clone and install DT in publisher

---

.github/workflows/publish-packages.yml

The old command set the store for a single project, which I didn't even know was possible. This instead grabs the default store dir (which I do in my projects and did on DT, though it is commented out).

Use the default pnpm cache dir rather than setting a new one

---

.changeset/hungry-jeans-love.md
packages/definitions-parser/src/get-affected-packages.ts
packages/definitions-parser/src/git.ts
packages/definitions-parser/test/get-affected-packages.test.ts
packages/definitions-parser/test/git.test.ts

even if they're missing package.json
Moves gitDeletions from git.ts to get-affected-packages, sorry for the churn.
Edit: less churn, still churny.

Check newly added packages

---

.changeset/dirty-walls-drum.md
packages/definitions-parser/package.json
pnpm-lock.yaml

Otherwise you get:
```
node_modules/.pnpm/@definitelytyped+definitions-parser@0.0.179_typescript@5.3.0-dev.20231018/node_modules/@definitelytyped/definitions-parser/dist/packages.d.ts:4:25 - error TS7016: Could not find a declaration file for module 'semver'. '/home/jabaile/work/DefinitelyTyped/node_modules/.pnpm/semver@7.5.4/node_modules/semver/index.js' implicitly has an 'any' type.
Try `npm i --save-dev @types/semver` if it exists or add a new declaration (.d.ts) file containing `declare module 'semver';`
4 import * as semver from "semver";
```

Add semver types to dependencies in definitions-parser

---

.changeset/thick-tigers-cry.md

#757 was missing changesets, so got partially published breaking downstream importers:
```
node_modules/.pnpm/@definitelytyped+definitions-parser@0.0.180_typescript@5.3.0-dev.20231018/node_modules/@definitelytyped/definitions-parser/dist/packages.d.ts:1:10 - error TS2305: Module '"@definitelytyped/header-parser"' has no exported member 'Contributor'.
1 import { Contributor, Header, License } from "@definitelytyped/header-parser";
~~~~~~~~~~~
```

Add changeset for #757

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Just what it says on the tin. In support of DefinitelyTyped/DefinitelyTyped#67144.

Add ` vscode-languageserver-types` to allowed dependencies

---

packages/publisher/src/calculate-versions.ts

If we're publishing types packages which depend on each other, `pacote` isn't going to resolve to them. I'm not sure how this worked before (this code appears to have existed before the pnpm branch); for now this unblocks publishing by not checking types packages which exist in the repo (albeit without a version check).

Fix publish of interdependent packages

---

.changeset/neat-countries-retire.md
packages/definitions-parser/src/get-affected-packages.ts

This should unblock https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67128; we only want to be collecting info on changed `@types/` packages here.

Ignore non-types packages when checking for changed packages

---

.changeset/mighty-falcons-matter.md
packages/dts-critic/index.ts

This would unblock https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67120, but I actually think these two uses could just be `pacote` + https://www.npmjs.com/package/@andrewbranch/untar.js or something.

Disable corepack when we run npm

---

.changeset/nervous-dancers-argue.md
packages/definitions-parser/src/get-affected-packages.ts

Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/67205
I think I probably incorrectly suggested the bad code in a change, not understanding what this code did. This just removes `...` which gives the right answer on DT:
```
dtslint-runner@0.0.188
Node version:  v20.9.0
Using local DefinitelyTyped at .
Running: git rev-parse --verify master
d0df83268470773861ff1bd2a6a9520b8c247d3d
Running: git diff master --name-status
M       types/node/v18/child_process.d.ts
M       types/node/v18/test/child_process.ts
Testing 1 changed packages: Set(1) { 'node/v18' }
Testing 9 dependent packages: Set(9) {
'ssh2',
'docker-modem',
'dockerode',
'docker-events',
'node-ssh',
'promise-sftp',
'ssh2-sftp-client',
'ssh2-sftp-client/v7',
'tunnel-ssh'
}
```

Fix dependent packages showing up as changed in getAffectedPackages

---

README.md

The URL in the markdown file was incorrectly formatted with double 'https://' at the beginning. This commit removes the extra 'https://' to ensure the link points to the correct address.

Fix: broken URL in documentation

---

.changeset/gorgeous-colts-prove.md
packages/definitions-parser/src/git.ts
packages/definitions-parser/test/git.test.ts
packages/dtslint-runner/src/prepareAffectedPackages.ts

An effect of #761 was to make PRs fail if they ever deleted a file, no matter where. This means PRs like my PR that deletes scripts fails because deleting files is now banned, which doesn't feel right.
Also, fix a case where errors were not propagated upward, which was the root cause of the tooling hiding the error for the script PR. I think we may want to consider using a real generic result type; working with these error arrays and ensuring they're nonempty is getting a little fickle...

Allow PRs to delete files, fix error passing

---

.changeset/forty-houses-grow.md
packages/header-parser/src/index.ts
packages/header-parser/test/index.test.ts

Required for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67090 to pull in a specific version of `marked` for testing, while allowing a wide dependency range for publishing

Remove pnpm validation from header-parser

---

.github/workflows/ci.yml
packages/definitions-parser/allowedPackageJsonDependencies.txt

This adds a CI check that verifies that PRs contain changesets if they modify packages, ignoring PRs which only modify `allowedPackageJsonDependencies.txt`.
```
🦋  error Some packages have been changed but no changesets were found. Run `changeset add` to resolve this error.
🦋  error If this change doesn't need a release, run `changeset add --empty`.
```

Enforce changesets in PRs (excluding allowedPackageJsonDependencies)

---

.changeset/strange-eagles-hope.md
packages/definitions-parser/src/get-affected-packages.ts

This unblocks https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67259. See https://github.com/DefinitelyTyped/DefinitelyTyped/actions/runs/6708512678/job/18229483924?pr=67259
```
M	types/node/v18/ts4.8/test/stream.ts
AssertionError [ERR_ASSERTION]: bad path scripts
at assertDefined (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+utils@0.0.182/node_modules/@definitelytyped/utils/src/assertions.ts:7:9)
at <anonymous> (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+definitions-parser@0.0.186_typescript@5.3.0-dev.202[31](https://github.com/DefinitelyTyped/DefinitelyTyped/actions/runs/6708512678/job/18229483924?pr=67259#step:7:32)031/node_modules/@definitelytyped/definitions-parser/src/get-affected-packages.ts:9 …
```

Ignore non-types packages returned by pnpm

---

.github/workflows/ci.yml

This unblocks #804. It's technically feasible that someone reverts a changeset in a PR (bringing the count to zero) but also changes a package intentionally, but that is nearly indistinguishable from the versioning PR.

Fix changeset check failure on versioning PR

---

.changeset/forty-teachers-push.md
packages/eslint-plugin/src/rules/no-unnecessary-generics.ts
packages/eslint-plugin/test/no-unnecessary-generics.test.ts

This PR addresses https://github.com/microsoft/DefinitelyTyped-tools/issues/734 and is a result of pairing with the ever kind and generous @joshuakgoldberg.
When working on the formatting of Definitely Typed, we happened upon some surprising behaviour around the `no-unnecessary-generics` rule. In the words of George Bernard Shaw: "I often quote myself. It adds spice to my conversation."  Let me quote me now:
> You'll note that we have an `eslint-disable-next-line` just before the last line; the ReturnType of the method.  Without this in place the red squigglies would be under:
> 
> ```ts
> JQuery<TElement>
>        ~~~~~~~~
> ```
> 
> This isn't the useful place to have this report.  Perhaps the better place would be the first mention of `TElement`, like so:
> 
> ```ts
>     <TElement …
```

fix: position of reporting ESLint rule no-unnecessary-generics

---

.changeset/five-bears-tickle.md
packages/definitions-parser/src/packages.ts
packages/definitions-parser/test/packages.test.ts

Partially unblocks DefinitelyTyped/DefinitelyTyped#67259 and DefinitelyTyped/DefinitelyTyped#67291
When doing type checking on CI, the package that depends on it might use it in the `scripts` folder while not using it in the `types` folder, causing the CI to fail from missing dependencies due to `pnpm` only installs packages which got affected
In DefinitelyTyped/DefinitelyTyped#67259 case `pnpm` installed packages for
```
es-abstract/scripts
get-intrinsic/scripts
lodash-es/scripts
material-ui/scripts
...
```
While the CI checks typing for
```
es-abstract
get-intrinsic
lodash-es
material-ui
...
```
This PR fixes that issue by skipping type checking for `scripts` folder

[definitions-parser] skip scripts folder

---

.changeset/tiny-pens-rush.md
packages/utils/src/io.ts

I broke this in #818.
Old code:
```ts
export function writeJson(path: string, content: unknown, formatted = true): Promise<void> {
return writeJsonRaw(path, content, { spaces: formatted ? 4 : 0 });
}
```
What I replaced it with:
```ts
export function writeJson(path: string, content: unknown, formatted = true): Promise<void> {
return fs.promises.writeFile(JSON.stringify(content, undefined, formatted ? 4 : undefined), path);
}
```
Sigh

Fix writeJson helper after incorrect refactor

---

.changeset/serious-dots-press.md
packages/eslint-plugin/src/configs/all.ts
packages/eslint-plugin/src/index.ts
packages/eslint-plugin/test/eslint.test.ts

Previously, this test required a self link and built artifacts. I didn't notice the latter as a problem because I usually run using the Ctrl+Shift+B watch build. But, it's not so good when editing and you aren't using that.
Instead, we can provide the plugin ahead of time, which causes ESLint to not try and find it on disk.
This required some changes to make the plugin's imports resolve when transpiled by ts-jest. Would be nice to get rid of that gotcha at some point but at the moment we're still fully CJS.
Tested by:
```console
$ git clean -fdx -e '/.vscode'
$ pnpm i
$ (cd packages/utils; pnpm build)
$ pnpm test -- eslint-plugin
```

Run eslint test using plugin loaded by tests, not built

---

.github/workflows/update-ts-version-tags.yml

I removed this in my PR which got rid of cloning, but I didn't realized that this CI job _never_ worked without a full clone. So, restore it until we can determine if we can avoid a clone.

Fix retag CI job by restoring clone

---

.changeset/fifty-flowers-clean.md
packages/definitions-parser/src/get-affected-packages.ts

Unblocks https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67463
We really need some sort of test suite for this code.
Also, I really am surprised that we don't have this helper somewhere else. That and I'm eternally confused by `typesDirectoryName` versus `subDirectoryPath`, as well as packages which are missing dirs and versions?

Fix getAffectedPackages for PRs which modify only versioned dirs

---

.changeset/sharp-roses-beam.md
packages/eslint-plugin/src/rules/no-import-of-dev-dependencies.ts
packages/eslint-plugin/src/rules/no-relative-import-in-test.ts
packages/eslint-plugin/src/rules/no-self-import.ts
packages/eslint-plugin/src/util.ts
packages/eslint-plugin/test/__file_snapshots__/types/no-import-of-dev-dependencies/bad.d.ts.lint
packages/eslint-plugin/test/__file_snapshots__/types/no-import-of-dev-dependencies/index.d.ts.lint
packages/eslint-plugin/test/__file_snapshots__/types/no-import-of-dev-dependencies/no-import-of-dev-dependencies-tests.ts.lint
packages/eslint-plugin/test/__file_snapshots__/types/no-relative-import-in-test/index.d.ts.lint
packages/eslint-plugin/test/__file_snapshots__/types/no-relative-import-in-test/no-relative-import-in-test-tests3.ts.lint
packages/eslint-plugin/test/__file_snapshots__/types/no-relative-references/index.d.ts.lint
packages/eslint-plugin/test/__file_snapshots__/types/no-relative-references/v1/index.d.ts.lint
packages/eslint-plugin/test/__file_snapshots__/types/no-self-import/bad.d.ts.lint
packages/eslint-plugin/test/__file_snapshots__/types/no-self-import/index.d.ts.lint
packages/eslint-plugin/test/__file_snapshots__/types/no-self-import/no-self-import-tests.ts.lint
packages/eslint-plugin/test/__file_snapshots__/types/scoped__no-relative-references/index.d.ts.lint
packages/eslint-plugin/test/__file_snapshots__/types/scoped__no-relative-references/v1/index.d.ts.lint
packages/eslint-plugin/test/fixtures/types/no-import-of-dev-dependencies/bad.d.ts
packages/eslint-plugin/test/fixtures/types/no-import-of-dev-dependencies/index.d.ts
packages/eslint-plugin/test/fixtures/types/no-import-of-dev-dependencies/no-import-of-dev-dependencies-tests.ts
packages/eslint-plugin/test/fixtures/types/no-relative-import-in-test/index.d.ts
packages/eslint-plugin/test/fixtures/types/no-relative-import-in-test/no-relative-import-in-test-tests3.ts
packages/eslint-plugin/test/fixtures/types/no-relative-import-in-test/tsconfig.json
packages/eslint-plugin/test/fixtures/types/no-self-import/bad.d.ts
packages/eslint-plugin/test/fixtures/types/no-self-import/index.d.ts
packages/eslint-plugin/test/fixtures/types/no-self-import/no-self-import-tests.ts

This PR didn't fail: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67297/files#r1382334665
It turns out that a number of lint rules did not handle `import =` declarations and so went unchecked

Handle `import = require()` in lint rules

---

.changeset/popular-starfishes-listen.md
packages/eslint-plugin/src/index.ts
packages/eslint-plugin/test/eslint.test.ts

See: https://eslint.org/docs/latest/extend/plugins#meta-data-in-plugins
I'm still unclear why ts-eslint's rule creator is incompatible with ESLint's rule types, but this PR only moves the cast.

Fully type eslint plugin export and add metadata

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

So we can deprecate react-native https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67459

Add react-native to allowedPackageJsonDependencies.txt

---

.changeset/fast-rocks-exist.md
packages/dtslint-runner/expectedFailures.txt

DT packages that depend on knex (which ships its own types) have started failing on TS 5.4 due to https://github.com/microsoft/TypeScript/pull/56004.

Add knex dependents to expected failures

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

redux-saga publishes a separate repo for certain types.

Add `@redux-saga/types` to allowedPackageJsonDependencies.txt

---

.changeset/curly-starfishes-check.md
packages/eslint-plugin/package.json
pnpm-lock.yaml

Commit 6da1cb1bfb3e787122536ff14fd09194c8b55cbe started to use `context.sourceCode` property, which is introduced in ESlint v8.40.0.[^eslint-8.40.0]
This patch updates the peerDependency for `eslint` to require that version or later. The change will help users using `@definitelytyped/eslint-plugin` outside of DefinitelyTyped properly manage their dependencies.
[^eslint-8.40.0]: https://eslint.org/blog/2023/05/eslint-v8.40.0-released/

eslint-plugin: Require eslint ^8.40.0 as peerDependency

---

.changeset/twenty-timers-march.md
packages/dtslint-runner/expectedFailures.txt

`knex` just published a new version that doesn't have the error that caused `knex-cleaner` to fail on 5.4.
`knex-db-manager` will still fail because it depends on and older `knex` version.

Remove knex-cleaner from expected failures

---

.changeset/khaki-eggs-jam.md
packages/dtslint/src/index.ts

Special-cased for the way `pnpm test` will invoke dtslint on DT.

Useful error on `pnpm test` without arguments

---

.changeset/thirty-cows-think.md
packages/dtslint/src/lint.ts

Things were only working on my machine because my build output dir wasn't clean and so tslint was able to find rules.
Just remove the code that fails due to there being no rules. Not a full removal of tslint at all, just enough to make it work.

Remove more tslint code to make dtslint work again

---

.changeset/fuzzy-ducks-knock.md
packages/dtslint-runner/package.json
packages/dtslint-runner/src/main.ts
pnpm-lock.yaml

I removed the code that generated these files in #843; maybe I should restore it, but it's not super clear to me we can do so now that we're in eslint and running per-file and not a full compilation.

Remove performance logging

---

.changeset/moody-geese-stare.md
packages/dtslint/src/lint.ts

When `expectOnly` is on, we force eslint to _only_ load that one rule, no configs, etc.
But, in #681 I forced `npm-naming` on via a base config, but forgot to delete that base config in `expectOnly`. This had the effect of spurious failures when running unrelated packages as `npm-naming` would be enabled while `useEslintrc` was _disabled_, meaning no package's config was being applied.
The fix is to reset the config more.
I want to rewrite this to not be so side-effect-y (e.g. add a `getEslintOptions` function), but that can come later. Right now, this is just breaking people's PRs.

Fix expectOnly enabling npm-naming

---

package.json

Packages matching this pattern are intentionally outdated but clutter `pnpm outdated -r`.

Ignore typescript-*.* in pnpm outdated

---

.changeset/config.json

```
npm notice Publishing to https://registry.npmjs.org/ with tag latest and public access
npm ERR! code E403
npm ERR! 403 403 Forbidden - PUT https://registry.npmjs.org/dts-gen - You do not have permission to publish "dts-gen". Are you logged in as the correct user?
npm ERR! 403 In most cases, you or one of your dependencies are requesting
npm ERR! 403 a package version that is forbidden by your security policy, or
npm ERR! 403 on a server you do not have access to.
npm ERR! A complete log of this run can be found in: /home/runner/.npm/_logs/2023-12-15T19_04_21_822Z-debug-0.log
 ELIFECYCLE  Command failed with exit code 1.
Error: Error: The process '/opt/hostedtoolcache/node/20.10.0/x64/bin/pnpm' failed with exit code 1
Error: The process '/opt/hostedtoolcache/node/20.10.0/x64/bin/pnpm' …
```

Ignore dts-gen for now, can't publish

---

.changeset/chilly-ears-allow.md
packages/dtslint/src/index.ts

Add a throw early on in dtslint. This isn't testable and stops linting, but is simple and obvious, making it easy to remove when we stop requiring index.d.ts.

Require index.d.ts

---

.changeset/khaki-phones-press.md
packages/eslint-plugin/src/rules/expect.ts

only on .ts files with $ExpectType in the editor.
Previously, this was how it ran in CI too, but Expect is the only compile there, so needs to run on everything.
Note: Code inside the visitor also checks context.options[0].versionsToTest.length, but that check *also* narrows, so I didn't dedupe the calculation. Suggestions welcome.

run Expect in all files on CI

---

.changeset/purple-flies-provide.md
packages/dtslint-runner/src/index.ts
packages/dtslint-runner/src/main.ts
packages/dtslint-runner/src/types.ts
packages/dtslint/src/index.ts
packages/dtslint/src/lint.ts

Previously, everything was skipped except for expect. This will be
slower, but will catch more errors. Now that we're running only eslint,
it should be fast enough, but I'll test with a node PR after this ships.

Skip only npm naming in dependents

---

.changeset/six-years-mix.md
package.json
packages/definitions-parser/src/packages.ts
packages/dtslint-runner/package.json
packages/dtslint-runner/src/check-parse-results.ts
pnpm-lock.yaml

1. Don't require types dependencies to be on DT.
2. Allow types dependencies to be pinned.
3. Don't bother asserting that dependencies from package.json are in fact present in package.json.
The remaining check requires dependents to have a higher-or-equal minTypescriptVersion compared to their dependency. This should really be in dtslint, but I don't want to make the fix (too) complex. And I haven't gone to check whether dtslint has access to `allPackages`.

Loosen checkParseResults

---

.changeset/gentle-points-clean.md

Forgot to add it to #865. I'm not sure why CI passed without it.

Add missing changeset from previous PR

---

.changeset/serious-cougars-judge.md
packages/eslint-plugin/src/rules/expect.ts

This was caught on https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68126. Copy the check from https://github.com/microsoft/DefinitelyTyped-tools/blob/4ec06280828fbd22c48008dfbf423585ab8a2d87/packages/dtslint/src/checks.ts#L83.

Make node16 check in expect case insensitive

---

.changeset/strange-sheep-ring.md
packages/definitions-parser/src/get-affected-packages.ts
packages/definitions-parser/src/git.ts
packages/definitions-parser/test/git.test.ts

1. gitDiff parses git moves from R*nnn* *from* *to* to `{ status: "R", file: to, source: from }`.
1. gitChanges converts `R` to an add and a remove.
3. Documentation of gitChanges, especially in relation getAffectedPackages.
4. Test of gitChanges!
5. No more circular dependency get-affected-packages.ts <-> git.ts. Now git.ts only depends on get-affected-packages.ts.
6. Dedupe call to (and error logging from!) gitChanges.
7. getAffectedPackages no longer returns any errors, only throws if `pnpm` execs fail.
The test case I added is pretty big, but it is real, and complicated. I can try to minimise it if anybody feels strongly that it should be.

Handle moves in gitChanges+other cleanup

---

.changeset/funny-ravens-carry.md
.changeset/tiny-boats-prove.md
packages/dtslint-runner/src/main.ts
packages/eslint-plugin/src/suggestions.ts
packages/utils/package.json
packages/utils/src/fs.ts
pnpm-lock.yaml

This prevents DefinitelyTyped tools from polluting the user’s home directory.
Also the `suggestionsDir` is defined and exported once, so it can be reused.
Closes #387

Write suggestions to the cache dir instead of home

---

.changeset/plenty-melons-think.md
packages/dts-critic/develop.ts
packages/dts-critic/index.ts
packages/dts-critic/package.json
pnpm-lock.yaml

This should address https://github.com/DefinitelyTyped/DefinitelyTyped/issues/67921.
On Windows, `npm` can actually be `npm.cmd` or `npm.ps1` or similar, especially in the world of corepack. If we're using `child_process` directly and not though a helper or lib like `execa`, we need to call `which` on the command name.
Every other package goes through `@definitelytyped/utils`' `exec` helper, but dts-critic does not as it needs to be synchronous. I could go and extract a helper to make a sync variant, if that's more desirable, but I wasn't sure I wouldn't accidentally cause a behavior change.

Fix dts-critic on Windows, missing `which` calls before exec

---

.changeset/wicked-days-joke.md
packages/dtslint/src/checks.ts
packages/dtslint/src/util.ts
packages/dtslint/test/index.test.ts

Previously this was checked implicitly by the unused-files check. Now
it's handled only by .npmignore, which works for publishing but not for
CI -- in particular, it's easy to forget to put test files into
tsconfig, thereby skipping testing.
This fix is NOT foolproof, but it will prevent common mistakes while
allowing uncommon layouts. `.npmignore` will continue to make sure that stray files
don't get published.

Require one .d.ts, one .ts in tsconfig

---

.changeset/metal-geckos-worry.md
packages/dtslint-runner/src/main.ts
packages/dtslint/src/index.ts

This got dropped from #811 somewhere during merge conflict resolution.
Example output:
```
❯ pnpm test-all                                                        
> definitely-typed@0.0.3 test-all /Users/andrew/Developer/microsoft/DefinitelyTyped
> node --enable-source-maps node_modules/@definitelytyped/dtslint-runner/ --path .
dtslint-runner@0.1.5
Node version:  v21.6.1
Using local DefinitelyTyped at .
Running: git rev-parse --verify master
124c5f37d0e894d6fd10f832ffc4dd426a2c0fa5
Running: git diff master --name-status
M       types/xrm/index.d.ts
M       types/xrm/xrm-tests.ts
Testing 1 changed packages: Set(1) { 'xrm' }
Testing 0 dependent packages: Set(0) {}
1> xrm START
dtslint@0.2.5
1> xrm OK (with warnings)
=== SUGGESTIONS ===
{}
=== WARNINGS ===
Warnings in xrm
Ignoring npm …
```

Add missing warning logging to dtslint/dtslint-runner

---

.changeset/gorgeous-scissors-sell.md
packages/definitions-parser/src/get-affected-packages.ts
packages/definitions-parser/src/git.ts
packages/definitions-parser/src/packages.ts
packages/definitions-parser/test/packages.test.ts

Proposed fix for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68392#issuecomment-1918387474:
```
Error: Unexpected file added: types/node/ts4.8/scripts/html-doc-processing.ts
You should only add files that are part of packages.
at prepareAffectedPackages (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+dtslint-runner@0.1.5_typescript@5.4.0-dev.20240130/node_modules/@definitelytyped/dtslint-runner/src/prepareAffectedPackages.ts:24:11)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at runDTSLint (/home/runner/work/DefinitelyTyped/DefinitelyTyped/node_modules/.pnpm/@definitelytyped+dtslint-runner@0.1.5_typescript@5.4.0-dev.20240130/node_modules/@definitelytyped/dtslint-runner/src/main.ts:45:7)
at <anonymous> …
```

Don't error when scripts are modified

---

.changeset/cold-kiwis-relate.md
packages/definitions-parser/src/get-affected-packages.ts

This should unblock https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68392 and maybe https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68356
This code is in the untested part of our code, so, no test :(

Don't look for dependents of packages with deleted files if those packages were not fully deleted

---

.changeset/brave-deers-share.md
.changeset/mean-readers-lay.md
.changeset/red-carrots-yell.md
packages/definitions-parser/src/get-affected-packages.ts
packages/definitions-parser/src/git.ts
packages/definitions-parser/src/index.ts
packages/definitions-parser/src/lib/settings.ts
packages/dtslint-runner/src/index.ts
packages/dtslint-runner/src/main.ts
packages/dtslint-runner/src/prepareAffectedPackages.ts
packages/dtslint-runner/src/types.ts

Right now, dtslint-runner always diffs against `master`, fetching if not present. In CI, this causes problems because another user may have merged something to `master` just after the run has started; the view of `master` that CI has may not be the one that the PR's merge commit reflected, and so we'll attempt to run tests of packages that were not affected in the PR.
For `pnpm install`, I've already fixed this race by filtering to `...[HEAD^1]...`. Since PRs run in merge commits, `HEAD^1` (the first parent) is the base branch (master) and `HEAD^2` (the second parent) is the PR code from the user's fork. CI will have fetched these refs, so if we use these and never fetch, CI will always behave deterministically. The same applies to pushes to `master`; we squash commit so `HEAD^1` always …

Add --diffBase to configure diffing, stop fetching, other git improvements

---

.github/workflows/codeql.yml

Recent GITHUB_TOKEN changes broke our CodeQL workflow; copy the working one from TS to fix it.

Fix CodeQL workflow by copying new one from TS

---

.changeset/great-garlics-flash.md
packages/dts-gen/src/definitely-typed.ts

More or less goes with https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68529. Would be nice for people generating packages to start with node16.

Generate module=node16 in dts-gen

---

.changeset/weak-flowers-fail.md
packages/definitions-parser/src/get-affected-packages.ts
packages/definitions-parser/src/git.ts
packages/definitions-parser/test/get-affected-packages.test.ts
packages/definitions-parser/test/git.test.ts
packages/dtslint-runner/src/main.ts
packages/dtslint-runner/src/prepareAllPackages.ts
packages/dtslint/src/index.ts
packages/utils/src/collections.ts

For https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68558 (and others in the future)

Detect package names added/removed from attw.json as changed

---

.changeset/dull-pets-call.md
packages/dtslint/package.json
packages/dtslint/src/checks.ts
packages/dtslint/src/index.ts
packages/utils/src/io.ts
pnpm-lock.yaml

This should be a performance win, but is also preparation for fixing https://github.com/DefinitelyTyped/DefinitelyTyped/issues/67361 and bringing dts-critic suggestions back.

Run arethetypeswrong from in-memory tarball data

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

This PR:
DefinitelyTyped PR that requires this change: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68578

Add Reselect to the allowed list of external dependencies

---

.changeset/little-timers-reflect.md
packages/dtslint/src/checks.ts
pnpm-lock.yaml

Example output:
```
❯ pnpm test optimist
Debugger attached.
> definitely-typed@0.0.3 test /Users/andrew/Developer/microsoft/DefinitelyTyped
> node --enable-source-maps node_modules/@definitelytyped/dtslint/ types "optimist"
Debugger attached.
dtslint@0.2.7
Warnings:
Failed to extract implementation package from https://registry.npmjs.org/optimist/-/optimist-0.0.7.tgz. This is likely a problem with @arethetypeswrong/core or the tarball data itself. @arethetypeswrong/cli will not run. Error:
SyntaxError: Expected double-quoted property name in JSON at position 207
at JSON.parse (<anonymous>)
at extractTarball (/Users/andrew/Developer/microsoft/DefinitelyTyped-tools/node_modules/.pnpm/@arethetypeswrong+core@0.13.6/node_modules/@arethetypeswrong/core/src/createPackage.ts:285:28)
at …
```

Don’t crash when implementation package fails to extract

---

.changeset/chatty-jobs-pull.md
.changeset/fifty-points-eat.md
packages/dtslint/src/checks.ts
packages/dtslint/src/index.ts

This is a noisy change; meant to just send the PR to error if tslint.json is present, but found myself changing a few other things to prevent dtslint from bailing early for simple problems like "npmignore is wrong" or "OTHER_FILES.txt or tslint.json is present".
We'll now not bail out early on errors, e.g. 
putting some random garbage in a dts file in a types version dir:
```
dtslint@0.2.7
testing from 4.6 to 4.8 in /home/jabaile/work/DefinitelyTyped/types/node/ts4.8
testing from 4.9 to 5.4 in /home/jabaile/work/DefinitelyTyped/types/node
Error: 
/home/jabaile/work/DefinitelyTyped/types/node/ts4.8/cluster.d.ts
433:1  error  TypeScript@4.6, 4.7, 4.8 compile error: 
Statements are not allowed in ambient contexts  @definitelytyped/expect
433:1  error  TypeScript@4.6, 4.7, 4.8 compile error: …
```

Rework error collection, error if tslint.json is present

---

.changeset/eleven-emus-warn.md
packages/dtslint/expectedNpmVersionFailures.txt

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68667 - I think I'm doing this right...

fix: remove `aws-lambda` from expected npm version failures

---

.changeset/quiet-flies-develop.md
packages/eslint-plugin/src/rules/strict-export-declare-modifiers.ts
packages/eslint-plugin/test/__file_snapshots__/types/strict-export-declare-modifiers/good10.d.ts.lint
packages/eslint-plugin/test/fixtures/types/strict-export-declare-modifiers/good10.d.ts
packages/eslint-plugin/test/fixtures/types/strict-export-declare-modifiers/tsconfig.json

Motivated by:
```ts
import implementation = require("./implementation");
import polyfill = require("./polyfill");
import shim = require("./shim");
type Implementation = typeof implementation;
type Polyfill = typeof polyfill;
type Shim = typeof shim;
declare namespace index {
export import Flags = implementation.Flags;
const implementation: Implementation;
const polyfill: Polyfill;
const shim: Shim;
}
declare function index(re: ThisParameterType<Implementation>): implementation.Flags;
export = index;
```
This errors on the export even though it's required to get the right behavior and also _does not_ make all of the other namespace members unexported.

Don't complain about 'export import =' in strict-export-declare-modifiers

---

.changeset/thirty-pugs-compete.md
packages/dtslint/src/lint.ts
packages/eslint-plugin/src/rules/expect.ts
packages/eslint-plugin/test/fixtures/types/expect-diagnostics-versioned/.eslintrc.js

`settings` are global, cascading/merging options that get passed down to rules. When I moved `expect` to eslint, I didn't really know how they worked, so opted to use `Options`, which were hacky and required overrides.
But now we're wanting to check multiple tsconfigs, so we need somewhere to store that information. We can't add another option because `dtslint`'s options will totally override any user provided options. But if we use `settings`, they will merge together, so dtslint can set the TS versions, and the user can specify something like `extraTsconfigs: ["./tsconfig.dom.json"]`.

Switch expect to using settings for versionsToTest

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

I'm adding `@wordpress/keycodes` because checks are failing in this PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69133

Add `@wordpress/keycodes` to allowedPackageJsonDependencies.txt

---

.changeset/chilly-terms-rhyme.md
packages/dtslint/src/checks.ts

Some JSX frameworks don’t support the classic runtime. In order to support an automatic runtime other than `react`, they must specify the option `jsxImportSource`.
See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68955#issuecomment-2014831342

Allow the jsxImportSource compiler option

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Added `eslint-visitor-keys`, used in DefinitelyTyped/DefinitelyTyped#69145, to `allowedPackageJsonDependencies.txt`.

Add `eslint-visitor-keys` to `allowedPackageJsonDependencies.txt`

---

.github/dependabot.yml
.github/workflows/check-parse-results.yml
.github/workflows/ci.yml
.github/workflows/keepalive.yml
.github/workflows/publish-packages.yml
.github/workflows/publish-registry.yml
.github/workflows/update-ts-version-tags.yml
.github/workflows/version-or-publish.yml

This copies TS's config for dependabot, and then updates/pins all of our action uses.

Add dependabot config for GHA, pin actions

---

.changeset/clever-pens-bow.md
packages/dts-gen/src/definitely-typed.ts

I got this wrong when I updated dts-gen to the new versioning scheme. `version` is already major/minor.
see also https://github.com/DefinitelyTyped/DefinitelyTyped/pull/69355#discussion_r1565328208

Fix generated version in dts-gen

---

.changeset/chatty-stingrays-walk.md
packages/eslint-plugin/src/rules/expect.ts
packages/eslint-plugin/test/__file_snapshots__/types/expect/expect-tests.ts.lint
packages/eslint-plugin/test/fixtures/types/expect/expect-tests.ts

Noticed this when looking at a DT break; we were strict about there being exactly one space before and after `$ExpectType`, but silently ignored anything that didn't match that. There are quite a few `$ExpectType`s on DT that are being silently ignored!
Rather than being strict, this just ignores the extra whitespace.

Fix ExpectType with extra whitespace

---

.changeset/rude-ways-unite.md
packages/eslint-plugin/src/rules/expect.ts
packages/eslint-plugin/test/__file_snapshots__/types/expect/expect-tests.ts.lint
packages/eslint-plugin/test/fixtures/types/expect/expect-tests.ts

This was too breaky. There were a load more assertions that were uncaught.
I'll restore the bugfix later when I can sit down and run all of DT at once locally.

Revert "Fix ExpectType with extra whitespace (#1011)"

---

.changeset/sixty-items-sin.md
packages/eslint-plugin/package.json
packages/eslint-plugin/src/rules/expect.ts
packages/eslint-plugin/test/__file_snapshots__/types/expect-error-range/expect-error-range-tests.ts.lint
packages/eslint-plugin/test/__file_snapshots__/types/expect-error-range/index.d.ts.lint
packages/eslint-plugin/test/fixtures/types/expect-error-range/.eslintrc.js
packages/eslint-plugin/test/fixtures/types/expect-error-range/expect-error-range-tests.ts
packages/eslint-plugin/test/fixtures/types/expect-error-range/index.d.ts
packages/eslint-plugin/test/fixtures/types/expect-error-range/package.json
packages/eslint-plugin/test/fixtures/types/expect-error-range/tsconfig.json
pnpm-lock.yaml

This enables writing:
```ts
// @ts-expect-error >=5.5
```
Which means "only expect an error in 5.5 and above".

Support ts-expect-error for specific version ranges

---

.changeset/three-vans-fetch.md
packages/eslint-plugin/src/rules/expect.ts
pnpm-lock.yaml

There is some controversy over whether this is completely reliable, but it seems to work well in my tests, with and without `--max-old-space-size` passed in.
I initially tried to just stop adding new programs to the cache at a certain threshold, but somehow memory still shoots up after no more programs are being created at a modest heap usage. So we do this check and purge even if the current `getProgram` call didn’t eat up more memory itself.
This fixes the recent openui5 CI OOM.

Clear expect rule program cache when heap is almost exhausted

---

packages/mergebot/README.md
packages/mergebot/src/functions/pr-trigger.ts
packages/mergebot/src/run.ts

1. Update the webhook for manual card moves. The code compiles but I have no idea how to test it -- I don't know what the rules are for manual moves that the bot will respect.
2. Fix the "Should delete" output of run.ts to not print for open PRs, only closed and merged ones that were created, then closed, during the run of run.ts itself. Also add "Deleting" output when *actually* deleting a PR.
3. Fix one now-incorrect syntax for a `pnpm` call in the README (`--` is no longer needed).

New project board: 2 small followups

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Mapbox GL js [now has native types](https://github.com/mapbox/mapbox-gl-js/releases/tag/v3.5.0), so these are what should be imported for updated versions of child types.
Originally opened this to unblock the failing test at https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70144

chore: add mapbox-gl to allowedPackageJsonDependencies.txt

---

packages/retag/src/index.ts

https://github.com/microsoft/DefinitelyTyped-tools/actions/runs/10037065883 failed due to a 502 error, which should be retried. https://github.com/microsoft/DefinitelyTyped-tools/actions/runs/10140511504 failed due to a 400 error, which makes no sense.
Add some retries with a delay, ignore errors until we've seen too many.

Retry tags, exit only after too many errors

---

packages/mergebot/src/run.ts

I've been wondering why ancient PRs are on the board. The code here sorts the dates _ascending_, then throws away the first 50, deleting the rest. Except, that's the newest entries, which are the most important ones. Oops.

Keep the newest 50 merged PRs, not the oldest 50 merged PRs

---

packages/mergebot/src/pr-info.ts

A little overkill but I wanted to be sure.

Refactor suspicious config checking to be strongly typed

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

@types/three will need to depend on these types (see https://github.com/three-types/three-ts-types/pull/1173)

Add @webgpu/types to allowed external packages

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

@types/puppeteer-screenshot-tester will depend on the types self-declared by the sharp package (see [this PR on DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70435))

Add sharp to allowed external packages

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of DefinitelyTyped [PR #70571](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70571), `json-merge-patch` can be removed from expectedNpmVersionFailures.txt.

feat: Remove json-merge-patch from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of DefinitelyTyped [PR #70658](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70658), `random-string` can be removed from expectedNpmVersionFailures.txt.

feat: Remove random-string from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of DefinitelyTyped [PR #70665](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70665), `noisejs` can be removed from expectedNpmVersionFailures.txt.

feat: Remove noisejs from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of DefinitelyTyped [PR #70666](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70666), `multiparty` can be removed from expectedNpmVersionFailures.txt.

feat: Remove multiparty from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of DefinitelyTyped [PR #70675](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70675), `domurl` can be removed from expectedNpmVersionFailures.txt.

feat: Remove domurl from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of DefinitelyTyped [PR #70674](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70674), `milliseconds` can be removed from expectedNpmVersionFailures.txt.

feat: Remove milliseconds from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of DefinitelyTyped [PR #70686](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70686), `lazypipe` can be removed from expectedNpmVersionFailures.txt.

feat: Remove lazypipe from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of DefinitelyTyped [PR #70701](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70701), `merge-stream` can be removed from expectedNpmVersionFailures.txt.

feat: Remove merge-stream from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of DefinitelyTyped [PR #70708](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70708), `gulp-help-doc` can be removed from expectedNpmVersionFailures.txt.

feat: Remove gulp-help-doc from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of DefinitelyTyped [PR #70722](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70722), `svg-injector` can be removed from expectedNpmVersionFailures.txt.

feat: Remove svg-injector from expectedNpmVersionFailures.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

There are existing esbuild-plugin in the DT repo currently, including one of my ongoing [PR #70733](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70733). To facilitate adding or modifying these types in DT side, I would like to ask DT-tools maintainer to kindly accept and merge this PR.

feat: Add esbuild to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Needed for [DT PR #70863](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70863).
`focus-trap` has 1.4M weekly downloads, and only contain 1 dependency `"tabbable": "^6.2.0"` from its [package.json](https://github.com/focus-trap/focus-trap/blob/b20124419632e76c497ef9dd75c329e85f116b50/package.json#L66-L68)
I think it is reasonable to have it in DT-tool allowed dep list.

feat: Add focus-trap to allowedPackageJsonDependencies.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of [DT PR #70883](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70883), `rison` can be removed from expectedNpmVersionFailures.txt.

feat: Remove rison from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of [DT PR #70898](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70898), `natural-sort` can be removed from expectedNpmVersionFailures.txt.

feat: Remove natural-sort from expectedNpmVersionFailures.txt

---

.github/workflows/ci.yml

This workflow was checking `origin/main` rather than the merge base of the PR; due to race conditions or other timing issues with manual CI run approval, we may end up in a situation where the two are different, leading to other unrelated changes showing up in the diff during the changeset check. (Like https://github.com/microsoft/DefinitelyTyped-tools/actions/runs/11257648935/job/31524626555?pr=1075)

Fix missing changeset CI PR check

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of [DT PR #70979](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70979), `sleep` can be removed from expectedNpmVersionFailures.txt.

feat: Remove sleep from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of [DT PR #70961](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70961), `stream-meter` can be removed from expectedNpmVersionFailures.txt.

feat: Remove stream-meter from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of [DT PR #71002](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71002), `stream-series` can be removed from expectedNpmVersionFailures.txt.

feat: Remove stream-series from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of [DT PR #71041](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71041), `tz-format` can be removed from expectedNpmVersionFailures.txt.

feat: Remove tz-format from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of [DT PR #71061](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71061), `friendly-errors-webpack-plugin` can be removed from expectedNpmVersionFailures.txt.

feat: Remove friendly-errors-webpack-plugin from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of [DT PR #71062](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71062), `trayballoon` can be removed from expectedNpmVersionFailures.txt.

feat: Remove trayballoon from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of [DT PR #71072](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71072), `moment-business` can be removed from expectedNpmVersionFailures.txt.

feat: Remove moment-business from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of [DT PR #70990](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/70990), `run-sequence` can be removed from expectedNpmVersionFailures.txt.

feat: Remove run-sequence from expectedNpmVersionFailures.txt

---

.changeset/sweet-crews-impress.md
packages/publisher/test/generate-packages.test.ts
packages/typescript-packages/package.json
packages/typescript-versions/src/index.ts
packages/typescript-versions/test/index.test.ts
pnpm-lock.yaml

Seemingly forgotten at the release of 5.6.
When 5.7 comes out, 4.9 will be dropped too.

Update TS versions; removing 4.8, shipping 5.6, supporting 5.8

---

.gitignore
packages/publisher/test/isAlreadyDeprecated.test.ts

I guess in CI, we put the cache in a dir in the repo instead of tmp. Ignore that dir so the changeset workflow doesn't commit it, and then also make the CI check consistent with other uses.

Fix cache being checked in by changesets

---

.changeset/khaki-peas-relate.md
.changeset/tiny-camels-return.md
package.json
packages/definitions-parser/package.json
packages/dts-critic/package.json
packages/dts-gen/package.json
packages/dtslint/package.json
packages/eslint-plugin/package.json
packages/mergebot/package.json
packages/publisher/package.json
packages/publisher/test/generate-packages.test.ts
packages/typescript-packages/package.json
packages/typescript-versions/src/index.ts
packages/typescript-versions/test/index.test.ts
pnpm-lock.yaml

The current 8 supported versions are 5.0 to 5.7.

Drop support for TS 4.9, mark TS 5.7 as shipped

---

packages/publisher/src/generate-packages.ts
packages/publisher/test/__snapshots__/generate-packages.test.ts.snap
packages/publisher/test/generate-packages.test.ts

`react-dom` used to look like:
But now looks like this after adding peer deps:
When I added peer deps, I missed that I screwed up this formatting.

Fix incorrect newlines in package readmes with peer deps

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

This unblocks https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71428 (and it's already a dep of `tape`, so anyone with `@types/tape` should already have it)

add `mock-property` to the list of allowed deps

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of [DT PR #71003](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71003), `shortid` can be removed from expectedNpmVersionFailures.txt.

feat: Remove shortid from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of [DT PR #71074](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71074), `moment-precise-range-plugin` can be removed from expectedNpmVersionFailures.txt.

feat: Remove moment-precise-range-plugin from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Upon successful merge of [DT PR #71101](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71101), `react-s-alert` can be removed from expectedNpmVersionFailures.txt.

feat: Remove react-s-alert from expectedNpmVersionFailures.txt

---

.github/workflows/publish-packages.yml
.github/workflows/publish-registry.yml
.github/workflows/update-ts-version-tags.yml

If a publish run happens while retag is occurring, the retag can stomp on the tags the publisher just updated. This race is rare, but we just saw this with `@types/three`.
Set all of the "publish"-y workflows to the same concurrency group.

Do not concurrently publish to npm

---

packages/mergebot/src/functions/discussions-trigger.ts
packages/mergebot/src/functions/pr-trigger.ts

Makes the app less unhappy on bad inputs / timeouts.

Return 400 error on bad JSON in mergebot

---

.changeset/little-pugs-lick.md
packages/typescript-packages/package.json
packages/typescript-versions/src/index.ts
packages/typescript-versions/test/index.test.ts
pnpm-lock.yaml

Nightly is now 5.9; start testing it.

Support TS 5.9

---

packages/mergebot/src/util/util.ts

The bot doesn't need to ping another bot for reviews.

Ignore copilot reviewer account in mergebot

---

.changeset/purple-donkeys-press.md
packages/dtslint/src/lint.ts
packages/eslint-plugin/src/rules/expect.ts

These changes make styled-components stop OOMing on my machine; we churn through Programs more than we should but at least we get through it.

More aggressively drop Programs to prevent OOMs

---

packages/dtslint/expectedNpmVersionFailures.txt

For once https://github.com/DefinitelyTyped/DefinitelyTyped/pull/72360 landed

feat: Remove use-sync-external-store from expectedNpmVersionFailures.txt

---

packages/dtslint/expectedNpmVersionFailures.txt

Aim to remove unneeded packages from `expectedNpmVersionFailures.txt`, by hacking current dtslint implementation to check whether or not target packages will emit `"... can be removed from expectedNpmVersionFailures.txt in ..."` warning.
<details>
<summary>
Step 1. Add <code>packages/dtslint/src/check-package-in-expectedVersionFailures.ts</code> into <b>DT-tools repo</b>, and run <code>pnpm build</code>. <i>Note: Core logics are copied from <code>packages/dtslint/src/index.ts</code>. Hope they are correcly done :)</i>
</summary>
```ts
#!/usr/bin/env node
import { getTypesVersions } from "@definitelytyped/header-parser";
import fs from "fs";
import { basename, dirname, join as joinPaths } from "path";
import {
checkNpmVersionAndGetMatchingImplementationPackage,
checkPackageJson,
} from …
```

feat: Remove pkg from expectedNpmVersionFailures by hacking dtslint

---

.changeset/ten-crews-thank.md
packages/dtslint-runner/src/main.ts

This has bugged me for a while; when a package breaks (e.g. react right now), we're effectively guaranteed to place all of that package's versions into different shards, so CI will have failures spread across multiple logs. That's pretty annoying to gauge how broken something is.
This PR modifies our shading algorithm to group packages and then shard on those groups, placing `react`/`react/v18`, or `node`/`node/v20`/`node/v18`, etc, all in the same shard to fail together.
Probably it'd also be worth it to place something like `react` with `react-dom`, since those are also pretty much guaranteed to be in separate CI jobs.
Another fix would be to _not_ round robin shard the packages, instead group them directly alphabetically, however I think that might have the negative effect of making CI …

Place all versions of a single package into the same shard

---

.changeset/dull-balloons-look.md
packages/dtslint/src/index.ts
packages/header-parser/src/index.ts

I very much don't like this, but this makes it a warning (not a hard error) to leave older types versions behind untested.
See also DefinitelyTyped/DefinitelyTyped#72320

Warn on unsupported versions but validate, skip tests

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

three.js uses it in some of their addons (https://github.com/three-types/three-ts-types/pull/1602)

Add @dimforge/rapier3d-compat to allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Related PR: DefinitelyTyped/DefinitelyTyped#73093
A few types from the eslint package are used to define a plugin here. The `@types/eslint` package no longer exists (removed in DefinitelyTyped/DefinitelyTyped#70735), so that can't be used.

Add eslint to allowed packages

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

they ship their own types now.
will enable [this PR](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/73174) to be merged

add svgo to allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Related PR: DefinitelyTyped/DefinitelyTyped#73830
The `chai` package uses and re-exports the `AssertionError` class from this package.

Add `assertion-error` to allowed dependencies
