microsoft/DefinitelyTyped-tools

azure-pipelines.yml

The script used a specific version, but guardian revs all the time.

Use standard guardian tasks, not a manual script

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

This is a prerequisite for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/45510. Thanks! 🙌🏼

Add hot-shots to `allowedPackageJsonDependencies.txt`

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Pre-requisite for DefinitelyTyped/DefinitelyTyped#45775. 
Thanks 🙌🏼

Add `typeorm` to `allowedPackageJsonDependencies.txt`

---

CODEOWNERS

This might be too many notifications!

Add CODEOWNERS for notifications

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Added [`@apollo/client` ](https://github.com/apollographql/apollo-client)
Required for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46191

Added @apollo/client to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/46308

Add `boxen` to `allowedPackageJsonDependencies.txt`

---

.github/workflows/deploy.yml

Adds button to deploy types-publisher
Closes #1

Replace magic comment with workflow_dispatch

---

packages/dtslint-runner/expectedFailures.txt

Electron shipped a new version with fixed types.

Electron dependents are fixed

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

See: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47102

Allow ssim.js

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Let's allow to reference popular animation package that comes
with built-in types.
Thanks!
x-ref: DefinitelyTyped/DefinitelyTyped#47464

feat(lottie-web): new allowed package

---

packages/definitions-parser/src/get-affected-packages.ts
packages/definitions-parser/src/mocks.ts
packages/definitions-parser/src/packages.ts
packages/definitions-parser/test/get-affected-packages.test.ts
packages/definitions-parser/test/packages.test.ts
packages/definitions-parser/test/parse-definitions.test.ts
packages/definitions-parser/test/utils.ts

Make .allDependencyTypings() respect path mappings

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

See DefinitelyTyped/DefinitelyTyped#47869

Whitelist fs-jetpack

---

packages/utils/src/io.ts

I don‘t actually think attaching event handlers after starting the stream matters, but it looks a little sketchy

Check status code and attach event handlers before starting pipe

---

packages/publisher/README.md

Update README.md for publisher package

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Since `webpack@5` types are included.
https://github.com/webpack/webpack/blob/master/types.d.ts

allowedPackageJsonDependencies: add `webpack`

---

packages/header-parser/test/index.test.ts
packages/typescript-versions/src/index.ts

I'll probably need to change the instructions a bit more when I make step 4 happen in a github action, but I haven't started on that yet, so I'll leave it till then.

Add 4.2 support

---

packages/dtslint-runner/expectedFailures.txt

But in a different way this time, with different dependents.

Electron is broken again

---

.github/workflows/update-ts-version-tags.yml

Probably not quite right, but this should be a good start.

Update TS version tags weekly

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

reflexbox: @emotion/styled now peer depends on @emotion/react

---

packages/header-parser/test/index.test.ts
packages/publisher/test/generate-packages.test.ts
packages/typescript-versions/src/index.ts

Ship TS 4.1, deprecate TS 3.2

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for DefinitelyTyped/DefinitelyTyped#49748
https://github.com/Automattic/juice/releases/tag/v7.0.0
Thanks!

feat(juice): whitelist juice package

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

To fix https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49819

Add semantic-ui-react to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For https://github.com/DefinitelyTyped/DefinitelyTyped/pull/49972.

Add async-done as allowed dependency

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50337

Add autoprefixer to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Related PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/50337

Add @types/autoprefixer to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51103

Add http-proxy-middleware to list of allowed package dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51183

Add pg-protocol to allowedPackageJsonDependencies.txt

---

packages/perf/src/cli/compare.ts

fix "Your local changes to the following files would be overwritten by checkout" error caused when installing dependencies modifying package.json
see:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/44671#issuecomment-642138999
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51262

fix failure due to local changes to package.json

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51392

chore: Add ci-info to whitelisted dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

So we can add typings for [react-final-form-html5-validation](https://www.npmjs.com/package/react-final-form-html5-validation) via https://github.com/DefinitelyTyped/DefinitelyTyped/pull/51524

adding react-final-form

---

packages/definitions-parser/src/mocks.ts
packages/definitions-parser/src/packages.ts
packages/definitions-parser/test/get-affected-packages.test.ts
packages/definitions-parser/test/git.test.ts
packages/publisher/src/lib/npm.ts
packages/publisher/test/generate-packages.test.ts

Ensures entries are unique.
Fixes #161

Make notNeededPackages.json an object

---

packages/definitions-parser/src/lib/settings.ts
packages/publisher/src/lib/settings.ts
packages/utils/src/lib/settings.ts

Prerequisite of moving publisher to Azure Functions

Allow STORAGE_DIR environment variable to determine where files are written

---

packages/perf/src/common/utils.ts

https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=93431&view=logs&j=275f1d19-1bd8-5591-b06b-07d489ea915a&t=40b1ee41-44d6-5bba-aa04-4b76a5c732e5 doesn’t make sense to me

Assert version in toPackageKey

---

packages/perf/src/common/utils.ts

Fix isVersionedBenchmark

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

As part of DefinitelyTyped/DefinitelyTyped#52294
We will need to start depending on fake-timers by the sinon types in DT.

add sinon fake timers

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Need to allow this to fix hapi typings.
https://github.com/hapijs/podium/blob/master/lib/index.d.ts

adding @hapi/podium to allowed package.json dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Allowing socket.io & socket.io-client as required by https://github.com/DefinitelyTyped/DefinitelyTyped/pull/52719

allow socket.io & socket.io-client

---

packages/definitions-parser/test/packages.test.ts

im not sure how useful these are, but i was looking around the repo to get some understanding of it and saw they weren't already covered by tests.
interestingly i noticed `fullNpmName` transforms scoped names to mangled names, but `fullEscapedNpmName` does not. maybe they are meant to behave the same?
a name of `@foo/bar` would result in `fullNpmName` being `@types/foo__bar` but `fullEscapedNpmName` being `@types%2f@foo/bar`. though i have a feeling maybe the names of these packages wouldn't be scoped anyway?
also, `NotNeededPackage#globals` returns `this.globals`, but surely thats an infinite loop unless im missing something? is there some precedence magic going on?

add tests for typingsdata

---

packages/publisher/src/generate-packages.ts
packages/publisher/test/generate-packages.test.ts

Feedback from https://github.com/microsoft/TypeScript/issues/44030#issuecomment-837409697

Adds a homepage link to the package json

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Corresponds to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53803.

Added @types/eslint & co to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53913#issuecomment-864415791.

Add devtools-protocol as allowed dependency

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/53881
But adding it will also cause to

Add missing firebase-admin dependency

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for: DefinitelyTyped/DefinitelyTyped#54277
Thanks!

add(azure/functions): new allowed dependency

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

This is related to DefinitelyTyped/DefinitelyTyped#54597
And required to pass tests in DefinitelyTyped/DefinitelyTyped#54597

Add scroll behavior to white list

---

yarn.lock

Mainly ppdates TS from to 4.1 -> 4.3 (and eslint/tslint/eslint-parser-y stuff)

Update TS version

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55011
See https://dev.azure.com/definitelytyped/DefinitelyTyped/_build/results?buildId=106675&view=logs&j=8635df7d-ecde-52a7-c7a8-84b998e35690&t=c264d665-0b79-59b7-7e04-9965cbe74860&l=20

Add svelte to allowedPackageJsonDependencies

---

packages/header-parser/test/index.test.ts
packages/publisher/test/generate-packages.test.ts
packages/typescript-versions/src/index.ts

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/54895
Turns out this was harder than just 1 PR 😂

chore: remove ts3.6 support

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55313

Add `@types/got`

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

This reverts part of commit 383abedd72df1df6a4dbf77b7a2a1e663de21b0a.
Adding back single package which is part of DT CI gate tests and fails due to this specific packae removal.
TBD: create proper entry on DT to handle this specific package updates
Thanks!

Revert partially "gapi update (#311)"

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/55978.

Add @types/react-select to allowPackageJsonDependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

required for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/56099

add js-logger to allowedPackageJsonDependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

See https://github.com/FormidableLabs/victory/blob/v36.0.1/packages/victory/src/index.d.ts

Add `victory` to `allowedPackageJsonDependencies`

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

See https://unpkg.com/browse/rc-tree@5.2.1/lib/index.d.ts

Add `rc-tree` to `allowedPackageJsonDependencies`

---

.github/workflows/update-ts-version-tags.yml

Also specify node version manually since setup-node's documentation recommends that.

Add workflow dispatch to update version tags

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

See `types` field in https://unpkg.com/browse/react-map-gl@6.1.0/package.json

Add `react-map-gl` to `allowedPackageJsonDependencies`

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

See `types` entry in https://unpkg.com/recharts@2.0.0/package.json

Add `recharts` to `allowedPackageJsonDependencies`

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for `pino` removal from DT:
DefinitelyTyped/DefinitelyTyped#57023
Thanks!

Add @types/pino to white listed packages

---

packages/dtslint-runner/package.json
packages/dtslint/package.json

Make dtslint dep of dtslint-runner

---

packages/definitions-parser/src/lib/settings.ts
packages/dts-critic/tsconfig.json
packages/dtslint/tsconfig.json
packages/publisher/src/publish-packages.ts
packages/publisher/src/publish-registry.ts
packages/utils/src/process.ts

This updates the build for some other packages to the newest version of Typescript. I'm not sure why.

Add dtslint and dts-critic to project build

---

packages/dtslint/package.json

it should now be bin/src/index.js not bin/index.js

fix dtslint package.json's main entry

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

This is needed to remove @types/sass

allow sass

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for v0 (older) support when removing from DT
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/57922

allow @types/busboy

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58074
This is the new PR for lesgo 0.7.2

Add lesgo new middy

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

The package will be removed from DT. 
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58216

add @types/history to allowed packages

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

The package will be removed from DT.
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58218

add @types/faker to allowed packages

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For https://github.com/DefinitelyTyped/DefinitelyTyped/pull/58784

fix: add `jest-matcher-utils`

---

.github/workflows/ci.yml
packages/dts-critic/package.json
packages/dtslint-runner/src/index.ts
packages/dtslint/package.json
packages/dtslint/src/index.ts
yarn.lock

Ensures packages don’t depend on old versions of each other.

Fix self-dependency versions

---

packages/dts-critic/index.ts

Fixes https://github.com/DefinitelyTyped/DefinitelyTyped/issues/56042

Account for `npm pack` bug

---

packages/dts-critic/index.test.ts
packages/dtslint/test/npm-naming/name/types/parseltongue/index.d.ts.lint
packages/dtslint/test/npm-naming/name/types/wenceslas/index.d.ts
packages/dtslint/test/npm-naming/name/types/wenceslas/index.d.ts.lint

parseltongue now exists, so change to wenceslas.

Change non-existent package name in tests

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For https://github.com/DefinitelyTyped/DefinitelyTyped/pull/59391

Add `chart.js` to allowed dependencies

---

packages/dts-critic/index.test.ts

Update the test after this change: https://github.com/microsoft/DefinitelyTyped-tools/commit/8665394ff115f155c42743131c9d3d324a9f5935#diff-10c5bfe73dff0cabd8209aff472ae7df7ec7651c6b37a5334fdb9ecf90a6ad74L1-R1

Update test position after upgrading Prettier

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Deleted in #463, all in gapi.client.*

Restore required package.json dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

DT PR: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/60498

Add analytics to allowed dependencies

---

packages/utils/src/lib/settings.ts
packages/utils/src/npm.ts

Reverts microsoft/DefinitelyTyped-tools#478

Revert "Fix cache dir path"

---

packages/dtslint-runner/expectedFailures.txt

Add 1 more mongoose dependent that I missed

---

.github/workflows/publish-registry.yml
package.json
packages/definitions-parser/package.json
packages/definitions-parser/src/check-parse-results.ts
packages/definitions-parser/src/git.ts
packages/definitions-parser/test/git.test.ts
packages/perf/src/measure/measurePerf.ts
packages/publisher/.gitignore
packages/publisher/package.json
packages/publisher/src/calculate-versions.ts
packages/publisher/src/crawl-npm.ts
packages/publisher/src/full.ts
packages/publisher/src/generate-packages.ts
packages/publisher/src/lib/npm.ts
packages/publisher/src/lib/settings.ts
packages/publisher/src/publish-packages.ts
packages/publisher/src/publish-registry.ts
packages/retag/package.json
packages/retag/src/index.ts
packages/utils/src/collections.ts
packages/utils/src/npm.ts
tsconfig.base.json
yarn.lock

@andrewbranch Thanks for trying https://github.com/microsoft/DefinitelyTyped-tools/pull/451, I've now moved the cache into `os.tmpdir()`, to address https://github.com/microsoft/DefinitelyTyped-tools/pull/480#issue-1266598918. Would you be willing to give it another go, when you have a chance?

Use pacote second attempt

---

packages/dtslint/src/lint.ts

Attempt 2: This time in the ESLint API setup
Also stop the double output while I'm here.

Disable config cascading

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Add `@types/parse5` as allowed for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61170

Add `@types/parse5` for parse5 removal

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Unblocks DefinitelyTyped/DefinitelyTyped#61581

Add @glimmer/component to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61624

fix: add `@types/long` to `allowedPackageJsonDependencies`

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61700

Allow yup as it provides it's own types.

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For https://github.com/DefinitelyTyped/DefinitelyTyped/pull/61752

Add @mui/material and @mui/types to allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for:
https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62207
Thanks!

Add @types/favicons to whitelist

---

packages/dtslint/src/rules/export-just-namespace.ts
packages/dtslint/test/export-just-namespace.test.ts

@JoshuaKGoldberg you're probably interested in this too.

export-just-namespace supports TSDeclareFunction too

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For DefinitelyTyped/DefinitelyTyped#62818.

Add @types/undertaker as allowed dependency

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required to remove 'svgo': DefinitelyTyped/DefinitelyTyped#62847
Thanks!

Add @types/svgo to allowed packages

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62834

Add @hotwired/turbo as allowed dependency

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/62883

Add @types/ioredis to allowed packages

---

packages/header-parser/test/index.test.ts
packages/typescript-versions/src/index.ts

5.0 is the new nightly version

Add Typescript 5.0 to typescript-versions

---

packages/publisher/package.json
yarn.lock

Might be needed to update the Function runtime to version 4.

Update to `@azure/functions@3`

---

.github/workflows/ci.yml
.github/workflows/publish.yml

Update node version of workflows

---

.github/codeql/codeql-configuration.yml
.github/workflows/codeql.yml

Copied from the TS repo. I hope that the config file supports globs!

Add codeql scanning

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

for: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63601

Add @hapi/hapi to allowed packages

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

for: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63604

Add @hapi/hoek to allowed packages

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

- `@ember/test-helpers`
- `ember-qunit`
- `ember-resolver`
[There is an accompanying PR to remove these from DT.](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63669)

Add 3 Ember packages to allowedPackageJsonDependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63903

chore: Add rimraf to allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63975

Allow @types/minimatch as dependency for types packages

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

See https://github.com/DefinitelyTyped/DefinitelyTyped/pull/63903

chore: Add @types/rimraf to allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for:
DefinitelyTyped/DefinitelyTyped#64202
Thanks!

[add] react-clock dependency for DT

---

packages/utils/src/process.ts

Once every 50 tasks, instead of every task. This should be enough to avoid most ooms without slowing down execution much at all.

dtslint-runner restarts children periodically

---

packages/definitions-parser/src/lib/definition-parser.ts

This can be done now that https://github.com/DefinitelyTyped/DefinitelyTyped/pull/64515 is merged.

Bring error for superfluous entry in OTHER_FILES back

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Needed for other wordpress type packages

Added @wordpress/core-data to allowedPackageJsonDependencies.txt

---

packages/dtslint-runner/src/post-results.ts

The on demand DT pipeline was switched to compare the branch results with the main results instead of nightly results, so I'm renaming things as appropriate.

Rename nightly to main when reporting on demand DT results

---

packages/dtslint-runner/src/prepareAffectedPackages.ts

In prep for improving this (go faster + not timeout randomly), I want to see how long it's taking.

Log time installDependencies takes

---

packages/definitions-parser/src/lib/module-info.ts
packages/definitions-parser/test/module-info.test.ts
packages/dtslint/src/checks.ts
packages/dtslint/test/index.test.ts

Related: https://github.com/DefinitelyTyped/dt-mergebot/pull/458

Allow --module node16

---

packages/publisher/package.json
packages/publisher/src/full.ts
packages/publisher/src/get-definitely-typed.ts
packages/publisher/src/main.ts
packages/publisher/src/publish-packages.ts
yarn.lock

It stays removed from publish-packages.ts

Revert appinsights removal

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Needed for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65867

Add rdfxml-streaming-parser to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Related to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/65911
Hopefully this gets merged :) have a nice day

add raw-body to allowedPackageJsonDep

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Context: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66073#discussion_r1271385806

Add prettier to allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Similar to https://github.com/microsoft/DefinitelyTyped-tools/pull/695
Requested by @sandersn in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66073#discussion_r1273860934

Add `@types/prettier` to allowed dependencies

---

packages/header-parser/test/index.test.ts
packages/typescript-versions/src/index.ts

This reverts commit 14b335737264df281d2f9e74e6196d0b58f83fe8.

Revert "Support 5.3 (#703)"

---

packages/eslint-plugin/src/configs/all.ts
packages/eslint-plugin/src/rules/index.ts

Corresponds to https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66292 -> https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66292#discussion_r1303614848.

Enabled @typescript-eslint/prefer-namespace-keyword

---

packages/definitions-parser/src/lib/definition-parser.ts
packages/definitions-parser/src/mocks.ts
packages/dts-critic/develop.ts
packages/dts-critic/index.ts
packages/header-parser/src/index.ts
packages/header-parser/test/index.test.ts

feat: add descriptor to header-parser parseHeaderOrFail errors

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66491

Add broccoli-plugin to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66762

add marked to allowedPackageJsonDependencies.txt

---

.github/workflows/version-or-publish.yml
package.json

Fix publishing and tagging

---

.npmrc

This file is `ini`, not `yml`.

Fix invalid syntax in npmrc

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For https://github.com/DefinitelyTyped/DefinitelyTyped/pull/66824

Add undici-types to allowedPackageJsonDependencies.txt

---

CODEOWNERS

Update CODEOWNERS to add me

---

.changeset/late-apes-turn.md
packages/publisher/src/full.ts
packages/publisher/src/util/util.ts

restore parse-definitions in publisher/full.ts

---

.github/workflows/update-ts-version-tags.yml
packages/retag/src/index.ts

pnpm install retag workflow

---

.changeset/sour-countries-shop.md
packages/publisher/src/publish-registry.ts
packages/utils/src/process.ts

Fix one more missing corepack issue

---

.changeset/tricky-taxis-judge.md
packages/dtslint/src/index.ts
packages/dtslint/src/rules/expectRule.ts

Mention package.json field, not header, when referring to minimumTypeScriptVersion

---

.changeset/sharp-colts-grin.md
.changeset/thin-tools-begin.md
packages/dtslint/src/rules/expectRule.ts
packages/eslint-plugin/src/rules/no-import-of-dev-dependencies.ts

Fixes #772 and https://github.com/DefinitelyTyped/DefinitelyTyped/pull/67090#discussion_r1367525696

node16 test fallbacks for old TS versions, fix dependency/devDependency import

---

.vscode/settings.json

Remove .vscode/settings.json, mistakenly left behind

---

.knip.jsonc

Not sure if we should just update the auto format action to format all files; wasn't sure if that would be dangerous or not.

Format missed files

---

.github/workflows/ci.yml

#805 worked on my machine, but I don't have pipefail enabled. CI does. Oops.

Make sure new changeset script works with pipefail

---

.github/workflows/publish-packages.yml
.github/workflows/update-ts-version-tags.yml

Now that files are static, we no longer need to do this.

Don't clone or install in CI

---

.changeset/hip-tips-trade.md
packages/eslint-plugin/package.json
pnpm-lock.yaml

Fix incorrect ts-eslint peer deps

---

.changeset/swift-wolves-trade.md
packages/dtslint-runner/expectedFailures.txt

remove knex-db-manager from expectedFailures.txt

---

.changeset/config.json
.changeset/proud-coats-hope.md
.github/workflows/ci.yml
.github/workflows/update-ts-version-tags.yml
.github/workflows/version-or-publish.yml
packages/definitions-parser/package.json
packages/definitions-parser/src/lib/settings.ts
packages/dts-critic/package.json
packages/dtslint-runner/package.json
packages/dtslint/README.md
packages/eslint-plugin/src/util.ts
packages/header-parser/package.json
packages/publisher/package.json
packages/retag/package.json
packages/typescript-packages/package.json
packages/typescript-versions/package.json
packages/utils/package.json

These are all of the bits and bobs here that need to change when we change the branch name.

Switch all dt-tools references from master to main

---

.changeset/six-meals-breathe.md
packages/dtslint/src/lint.ts

This new method should be less error prone.

Clean up eslint options building

---

.changeset/beige-bobcats-tap.md
packages/dts-gen/package.json

Perms should now be configured enough to be able to publish this.

Reattempt dts-gen release

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68161
Per suggestion here: https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68161#issuecomment-1885876469

Add @glimmer/manager and @glimmer/runtime to support DT PR

---

.changeset/gorgeous-hats-matter.md
packages/dtslint/src/checks.ts
packages/dtslint/test/index.test.ts

Allow tsx tests in tsconfig too

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Required for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/68437

add @floating-ui/react to allowed dependencies list

---

.changeset/swift-apes-tan.md
packages/dtslint/package.json
packages/dtslint/src/checks.ts
pnpm-lock.yaml

Manually tested by checking a package that should have been marked as `nonNpm` and then by running it with my WiFi off 🤷

Retry and ignore npm errors in dtslint

---

.github/codeql/codeql-configuration.yml
.github/workflows/codeql.yml

Copy codeql from ts-benchmarking

---

.changeset/dull-students-type.md
packages/typescript-packages/package.json
packages/typescript-versions/src/index.ts
packages/typescript-versions/test/index.test.ts
pnpm-lock.yaml

We were supposed to have done this when main switched to 5.6.

Add TypeScript 5.6

---

.changeset/eighty-dolls-train.md
packages/eslint-plugin/src/rules/expect.ts
packages/eslint-plugin/test/__file_snapshots__/types/expect/expect-tests.ts.lint
packages/eslint-plugin/test/fixtures/types/expect/expect-tests.ts
pnpm-lock.yaml

This re-does #1011, but with more tests fixing things to be correct.

Re-fix ExpectType

---

.changeset/nervous-spoons-obey.md
packages/eslint-plugin/src/configs/all.ts
packages/eslint-plugin/test/__snapshots__/plugin.test.ts.snap

For upcoming 5.6 deferred feature.

Allow @deferred

---

packages/mergebot/src/_tests/fixturedActions.test.ts
packages/mergebot/src/_tests/fixtures/70218/_downloads.json
packages/mergebot/src/_tests/fixtures/70218/_files.json
packages/mergebot/src/_tests/fixtures/70218/_response.json
packages/mergebot/src/_tests/fixtures/70218/derived.json
packages/mergebot/src/_tests/fixtures/70218/mutations.json
packages/mergebot/src/_tests/fixtures/70218/result.json
packages/mergebot/src/pr-info.ts

No tests because I couldn't get a working token to create a test case for DefinitelyTyped/DefinitelyTyped#70218

Fix a crash in tsconfig.json's configSuspicious

---

.changeset/sharp-cobras-approve.md
packages/typescript-packages/package.json
packages/typescript-versions/src/index.ts
packages/typescript-versions/test/index.test.ts
pnpm-lock.yaml

Should have done this a couple of days ago.

Add TypeScript 5.7

---

.changeset/fair-pigs-jog.md
packages/publisher/src/publish-registry.ts
packages/retag/src/index.ts
packages/utils/src/async.ts

Trying to fix https://github.com/microsoft/DefinitelyTyped-tools/issues/1056

Attempt to fix types-registry with retry / nAtATime

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Refs https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71156

Add posthtml-render to allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Refs https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71156

Add 11ty.ts to allowed dependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71273

Add antlr4 to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Needed for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71274

Add @wordpress/editor to allowed dependencies

---

packages/publisher/src/generate-packages.ts
packages/publisher/test/generate-packages.test.ts

Mock current date for licence test

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

For https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71527.

feat: add tedious to allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71579

add wordpress/shortcode allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

unblocks https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71785

add es-to-primitive as an allowed dep

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

for https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71917

feat: add cesium to allowedPackageJsonDependencies.txt

---

.changeset/large-squids-watch.md
packages/dtslint/README.md
packages/publisher/test/__snapshots__/generate-packages.test.ts.snap
packages/typescript-packages/package.json
packages/typescript-versions/src/index.ts
packages/typescript-versions/test/index.test.ts
pnpm-lock.yaml

Refs https://github.com/DefinitelyTyped/DefinitelyTyped/commit/25a3ab4dadc20e9656776f9ec1d5038928743cb2\
Refs https://github.com/DefinitelyTyped/DefinitelyTyped/pull/72320

Remove support for TypeScript 5.0

---

.github/workflows/ci.yml
.github/workflows/version-or-publish.yml
package.json
packages/mergebot/src/util/util.ts

New mandatory branch protection rules block pushes to main without using a PR, so this step no longer works.
Checking this before I fix my formatting problem.

Check formatting in CI, no auto push

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

It has definitions builtin.
- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/72363

Allow `parse-url`

---

packages/dtslint/expectedNpmVersionFailures.txt

see https://github.com/DefinitelyTyped/DefinitelyTyped/pull/71354

feat: remove xrm from expectedNpmVersionFailures.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

- https://github.com/DefinitelyTyped/DefinitelyTyped/pull/72490

Allow `git-up`

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Adding `cheerio` for DT PR https://github.com/DefinitelyTyped/DefinitelyTyped/pull/72495.

feat: add cheerio into allowedPackageJsonDependencies.txt

---

.github/workflows/daily.yml

GitHub blocked this repo, I guess.

Remove keepalive job from daily

---

.github/workflows/ci.yml

In order to enable required checks and also enable merge queues.

Add a CI job to manage required jobs, run on push / merge group

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Adding pixi.js for DT PR [#72804](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/72804)

feat: add pixi.js into allowedPackageJsonDependencies.txt

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Looking to fix https://github.com/DefinitelyTyped/DefinitelyTyped/pull/73061#issuecomment-3021078786 in https://github.com/DefinitelyTyped/DefinitelyTyped/pull/73165

Add proj4 to allowedPackageJsonDependencies

---

packages/definitions-parser/allowedPackageJsonDependencies.txt

Opening this PR, to facilitate `nodemailer` type update in DT.
- `@aws-sdk/client-ses`: https://www.npmjs.com/package/nodemailer/v/6.10.1?activeTab=code
- `@aws-sdk/client-sesv2`: https://www.npmjs.com/package/nodemailer/v/7.0.5?activeTab=code

feat: add @aws-sdk/client-ses(v2) to allowedPackageJsonDependencies

---

.changeset/nasty-insects-walk.md
packages/dtslint/src/index.ts

Noticed in a random PR's CI run.

Improve error message when npmignore is missing
